### ISSUE TITLE
Cannot get theme to work

### ISSUE THREAD

**Issue by alexghergh** [marlonrichert/zsh-snap#1]
So I tried to get the agnoster theme (as in your README example), but the only thing i get is:

```
.znap.source:shift:4: shift count must be <= $#
.znap.source:.:16: not enough arguments
```
when I try to source `.zshrc` or just restart the shell.

Is there something I missed?

Also, how would one go about adding a custom theme?

Thank you

**Comment by marlonrichert** [comment]
@alexghergh Sorry about the cryptic error message. I've now added more informative ones. Please try the following:
```zsh
znap clone https://github.com/agnoster/agnoster-zsh-theme.git
znap pull
```
Then restart your shell.

Does that work?

**Comment by alexghergh** [comment]
Right. So I cloned and pulled, but now I get this:

```
.znap.compile:4: command not found: add-zsh-hook
znap source: not enough arguments
```
For the reference, my .zshrc only contains:

```
source ~/.zsh/zsh-snap/znap.zsh

znap prompt agnoster
```
If I remove the prompt line, I only get the first error message.

**Comment by marlonrichert** [comment]
@alexghergh Please again `znap pull` and restart. It should be fixed now. Sorry about the hassle!

**Comment by alexghergh** [comment]
Thanky you, worked great!

Also thank you for the cool project, been looking for something lightweight like this for a while!

Closing.
