### ISSUE TITLE
znap command not fount

### ISSUE THREAD

**Issue by AliTajelsir** [marlonrichert/zsh-snap#107]
- Error `znap command not found` with commit 1a658fe
- Reverting to commit db994e4 solves the issue
- `zsh 5.8-7` in Termux

**Comment by marlonrichert** [comment]
I need a bit more info than that. Can you make me a minimal, reproducible test case, please?

**Comment by AliTajelsir** [comment]
- These are my `.zshrc` settings related to znap:
```
[[ -f $HOME/.local/share/znap/zsh-snap/znap.zsh ]] ||
        git clone https://github.com/marlonrichert/zsh-snap.git $HOME/.local/share/znap/zsh-snap/
source $HOME/.local/share/znap/zsh-snap/znap.zsh
znap source zsh-users/zsh-completions
znap eval pip-completion "pip completion --zsh # $PYENV_VERSION"
znap source marlonrichert/zcolors
znap eval zcolors "zcolors ${(q)LS_COLORS}"
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting
znap source zsh-users/zsh-history-substring-search
znap source softmoth/zsh-vim-mode
znap source kutsan/zsh-system-clipboard
znap source romkatv/powerlevel10k
alias zup='znap pull'
```
- Termux `0.117`, zsh `5.8-7`

**Comment by marlonrichert** [comment]
I tried your `.zshrc` file, but it does not reproduce the problem for me.

What OS are you on?

> - Error `znap command not found` with commit 1a658fe

Can you please copy-paste the _exact_ error message that you get?

**Comment by marlonrichert** [comment]
Can you try the following? 
```zsh
cd $(mktemp -d)
git clone --depth 1 https://github.com/marlonrichert/zsh-snap.git
print 'PS1="%# "
source zsh-snap/znap.zsh
znap source marlonrichert/zcolors
' > .zshrc
SHELL==zsh
exec -c zsh -fc "HOME=$PWD SHELL=$SHELL TERM=$TERM exec $SHELL -d"
```
Do you get the same error mesage?

**Comment by AliTajelsir** [comment]
- I get the following error when i try to source `znap`:
```
zsh-snap/znap.zsh:3: failed to load module: zsh/param/private
zsh-snap/znap.zsh:local:4: bad option: -P
```

**Comment by AliTajelsir** [comment]
I get the following error:
```
zsh-snap/znap.zsh:3: failed to load module: zsh/param/private
zsh-snap/znap.zsh:local:4: bad option: -P
zsh-snap/znap.zsh:source:5: no such file or directory: /scrip/init.zsh
/data/data/com.termux/files/usr/tmp/tmp.lgf4rAMbI3/.zshrc:3: command not found: znap
```

**Comment by marlonrichert** [comment]
How did you install `zsh`?

**Comment by AliTajelsir** [comment]
- I installed `zsh` with termux package manager `pkg`
```
zsh is /data/data/com.termux/files/usr/bin/zsh
/data/data/com.termux/files/usr/lib/zsh/5.8
"/data/data/com.termux/files/usr/lib/zsh/5.8/zsh/param/private.so": No such file or directory (os error 2)
```

**Comment by marlonrichert** [comment]
Please report to Termux that their `zsh` distro is broken.

**Comment by marlonrichert** [comment]
As a workaround, try to see if you can find `private.so` anywhere under your `$module_path`:
```zsh
ls -l $^module_path/**/private.so
```
If that turns up a file, move it to `/data/data/com.termux/files/usr/lib/zsh/5.8/zsh/param/private.so`

If it doesn't, you can try building from source.

**Comment by marlonrichert** [comment]
Ah, it appears they decided to explicitly not include certain modules: https://github.com/termux/termux-packages/blob/b8e2bdf8530dcb7080d5f6449d82e8d1c8b0b665/packages/zsh/build.sh#L34

You can open an issue or pull request with them to change this.

**Comment by AliTajelsir** [comment]
Thanks for the help!
