### ISSUE TITLE
`zsh_plugins/ohmyzsh/plugins/autojump/autojump.plugin.zsh:15: file: attempt to assign private in nested scope`

### ISSUE THREAD

**Issue by ptaranat** [marlonrichert/zsh-snap#109]
I'm getting a few errors in some Oh My Zsh plugins.
<details><summary>Ignore these as they are duplicates</summary>

```
znap source: file not found: plugins/bundler
znap source: file not found: plugins/cargo
znap source: file not found: plugins/docker
znap source: file not found: plugins/fd
znap source: file not found: plugins/rust
```

My `.zshrc`:
```
znap source ohmyzsh/ohmyzsh
znap source ohmyzsh/ohmyzsh \
  plugins/{bundler,cargo,docker,fd,rust}
```

I noticed the the errors happened in OMZ plugins that prefixed the plugin with underscore. Not sure what changed on znap or OMZ side since it was previously working before. The only thing I did was a `znap pull` and updated `ohmyzsh/ohmyzsh`.

Fixed by specifying the whole plugin path:
```
znap source ohmyzsh/ohmyzsh
znap source ohmyzsh/ohmyzsh \
  plugins/{bundler/_bundler,cargo/_cargo,docker/_docker,fd/_fd,rust/_rust}
```

But this still results in some errors. The only plugin that can be successfully sourced is `docker/_docker`. The rest fail with `_arguments:comparguments:325: can only be called from completion function`. This seems to be related to a Zsh completion issues.
</details>

With the `autojump` plugin, there is an error `.zsh_plugins/ohmyzsh/plugins/autojump/autojump.plugin.zsh:15: file: attempt to assign private in nested scope`

**Comment by marlonrichert** [comment]
This has been answered in #104 and #55.

**Comment by marlonrichert** [comment]
> With the `autojump` plugin, there is an error `.zsh_plugins/ohmyzsh/plugins/autojump/autojump.plugin.zsh:15: file: attempt to assign private in nested scope`

This is a combination of two errors outside Znap:
* There is a [bug with private variable scoping in Zsh](https://www.zsh.org/mla/workers/2021/msg01569.html).
* The `autojump` plugin [inadvertently creates a global variable called `file`](https://github.com/ohmyzsh/ohmyzsh/blob/190325049ef93731ab28295dbedf36d44ab33d7a/plugins/autojump/autojump.plugin.zsh#L15).

I’ll see if I can implement a workaround.

**Comment by ptaranat** [comment]
Thanks for doing the detective work and sharing the relevant issues. On the OMZ side, the workaround is very simple. In case someone stumbles on this, I put everything in a function. Alternative is to declare those variables in local scope.

https://github.com/ptaranat/omz-autojump/commit/347cc8b18d97e1ffe2ad99cc586739fc4339085a

----

On an unrelated note, is it possible for znap to specify which branch or tag to source from? For example, in vim-plug, you can do:
```
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }
```

I can put it in as feature request.

**Comment by marlonrichert** [comment]
> is it possible for znap to specify which branch or tag to source from?

Not at present. The easiest way to currently do this is to just do `git switch <branch>` in the repo where you want to switch the branch.

**Comment by marlonrichert** [comment]
> Thanks for doing the detective work and sharing the relevant issues. On the OMZ side, the workaround is simple. In case someone stumbles on this, I put everything in a function. Alternative is to declare those variables in local scope.
> 
> https://github.com/ptaranat/omz-autojump/commit/a6a9829b348113f9944a5053e29f78e536124b14

Perhaps you should submit that as a patch to OMZ?

**Comment by marlonrichert** [comment]
OK, the workaround is in place. The error should be gone now.

---

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂

**Comment by marlonrichert** [comment]
Reopening because of #174.
