### ISSUE TITLE
Instant prompt issue with kitty

### ISSUE THREAD

**Issue by jonjonw** [marlonrichert/zsh-snap#11]
I have a very basic config and it works with gnome-terminal but with kitty I get the error

```
.znap.prompt.precmd:echoti:5: no such terminfo capability: invis
```

I don't get the error when I remove the prompt line from my zshrc. I can also load the prompt manually without an error.

Here is my zshrc
```sh
source ~/.zsh/zsh-snap/znap.zsh
znap prompt agnoster

```

**Comment by marlonrichert** [comment]
Should be fixed now.
