### ISSUE TITLE
Make `git maintenance` optional

### ISSUE THREAD

**Issue by patrickli** [marlonrichert/zsh-snap#115]
Maybe an environment variable to turn this off? Because I am in a `WSL` environment with no cron facilities. So `git maintenance` can't run at a schedule.

**Comment by marlonrichert** [comment]
What happens when you run `git maintenance start` inside a repo on WSL?

**Comment by patrickli** [comment]
Nothing on the output. However `git` does the following:
* Add 3 maintenance cron entries in my per-user crontab.
* Add a `maintenance` section to my global `.gitconfig` listing the repo that I just ran `maintenance start` in.
* Set `maintenance.auto=false` and `maintenance.strategy=incremental` in local repo config.

Effectively this disables the automated maintenance when you do `git pull` and others and shift this into cron. On WSL where there is no running cron daemon no maintenance will run, ever, for any repo that is registered to do scheduled maintenance.

**Comment by marlonrichert** [comment]
Have you tried `sudo service cron start`?

**Comment by patrickli** [comment]
You can do that, but once you reboot the machine cron won't be started automatically, because WSL doesn't run a normal init process at start.

They have introduced an option to run a script on start in Windows Insider builds but that still depends on the user to produce a script to explicitly start cron. So there is no guarantee for cron to be available.
