### ISSUE TITLE
Znap compile parse error

### ISSUE THREAD

**Issue by patrickli** [marlonrichert/zsh-snap#116]
```
.znap.compile:278: parse error near `bindkey'
.znap.compile:zcompile:47: can't read file: /home/patrick/.local/share/zsh-snap/prezto/modules/editor/init.zsh
```

Using latest version 7a18a8468c5b2722bfa71ae5ce413696e8935df3. Didn't have this problem a few days ago so should be fairly recent.

**Comment by patrickli** [comment]
This doesn't fix it unfortunately. There are actually more errors than this one. If I delete all `.zwc` from my home directory and run znap compile I get,
```
.znap.compile:zcompile:47: can't write zwc file: /home/patrick/.local/share/zsh-snap/fast-syntax-highlighting/→chroma/-git.ch.zwc
.znap.compile:zcompile:47: can't write zwc file: /home/patrick/.local/share/zsh-snap/fast-syntax-highlighting/→chroma/main-chroma.ch.zwc
.znap.compile:278: parse error near `bindkey'
.znap.compile:zcompile:47: can't read file: /home/patrick/.local/share/zsh-snap/prezto/modules/editor/init.zsh
.znap.compile:3065: parse error near `}'
.znap.compile:zcompile:47: can't read file: /home/patrick/.local/share/zsh-snap/prezto/modules/prompt/external/powerlevel10k/internal/p10k.zsh
```

**Comment by marlonrichert** [comment]
> ```zsh
> .znap.compile:zcompile:47: can't write zwc file: /home/patrick/.local/share/zsh-snap/fast-syntax-highlighting/→chroma/-git.ch.zwc
> .znap.compile:zcompile:47: can't write zwc file: /home/patrick/.local/share/zsh-snap/fast-syntax-highlighting/→chroma/main-chroma.ch.zwc
> .znap.compile:278: parse error near `bindkey'
> .znap.compile:zcompile:47: can't read file: /home/patrick/.local/share/zsh-snap/prezto/modules/editor/init.zsh
> .znap.compile:3065: parse error near `}'
> .znap.compile:zcompile:47: can't read file: /home/patrick/.local/share/zsh-snap/prezto/modules/prompt/external/powerlevel10k/internal/p10k.zsh
> ```

Sorry, but I cannot reproduce any of that. Did you make sure to restart your shell after updating Znap?

**Comment by patrickli** [comment]
Huh. These files got compiled in the background without issues. Maybe because I was fiddling with my config while this was happening?

Thanks for looking at this and sorry for the trouble.
