### ISSUE TITLE
znap eval usage

### ISSUE THREAD

**Issue by jonjonw** [marlonrichert/zsh-snap#12]
I'm guessing that I'm just using it incorrectly but I'm having trouble running commands with `znap eval`.

Sourcing the zsh-autosuggestions installed on my system works just fine:
```sh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
```
But if I try to source it with `znap eval` it doesn't function:
```sh
znap eval zsh-autosuggestions 'source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh'
```

It does generate a file in my plugins directory:
```sh
% cd plugins && ls
zsh-autosuggestions.zsh
zsh-autosuggestions.zsh.zwc

% cat zsh-autosuggestions.zsh
#source\ /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
```

Am I missing something?

**Comment by marlonrichert** [comment]
Yeah, you are missing something: `znap eval` is meant only to replace/speed up `eval "$( foo )"` statements. Trying to source plugins with it won’t work. That’s what `znap source` is for. 🙂

I’ll try to update the Readme to make this clearer.

**Comment by jonjonw** [comment]
Thanks! Is there a good way to load plugins that are already installed on your system (but owned by root in a different directory) rather than cloning them?

**Comment by marlonrichert** [comment]
I think the easiest would be to symlink them into the same dir where you installed Znap. So, for example, if Znap is located in `~/.zsh/zsh-snap/`, then do
```zsh
% cd ~/.zsh
% ln -is /usr/share/zsh/plugins/zsh-autosuggestions zsh-autosuggestions
```
Then Znap will be able to find `zsh-autosuggestions` automatically when you put `znap source zsh-autosuggestions` in your `.zshrc` file.

**Comment by marlonrichert** [comment]
Documentation updated.
