### ISSUE TITLE
znap eval doesn't regenerate cached code

### ISSUE THREAD

**Issue by thepreacher** [marlonrichert/zsh-snap#13]
I have this code in my `.zshrc`: `znap eval asdf-direnv 'asdf exec direnv hook zsh'` that hooks direnv into asdf-vm. At the time of using `znap` the version of direnv was `2.23.1` so it created the file `asdf-direnv` with the following code in it:
```
_direnv_hook() {
  trap -- '' SIGINT;
  eval "$("/Users/user/.asdf/installs/direnv/2.23.1/bin/direnv" export zsh)";
  trap - SIGINT;
}
typeset -ag precmd_functions;
if [[ -z ${precmd_functions[(r)_direnv_hook]} ]]; then
  precmd_functions=( _direnv_hook ${precmd_functions[@]} )
fi
typeset -ag chpwd_functions;
if [[ -z ${chpwd_functions[(r)_direnv_hook]} ]]; then
  chpwd_functions=( _direnv_hook ${chpwd_functions[@]} )
fi
```

Now I've just updated direnv to `2.25.2` and the zsh now throws the error `_direnv_hook:2: no such file or directory: /Users/nahiable/.asdf/installs/direnv/2.23.1/bin/direnv` at the prompt every time. This is because the `2.23.1` in the above code needs to be `2.25.2`.

It appears the code `znap eval` caches the code once and doesn't regenerate it again even when the underlyting package changes version.

**Comment by marlonrichert** [comment]
Znap cannot detect whether a command's underlying package has changed, especially not in this case: The main command you're calling with `znap eval` is `asdf`, but what has actually changed is the version of `direnv`. There is no way for Znap to detect this.

There are 3 cases that will cause `znap eval` to regenerate a cache:
* If the cache is missing.
* If the first argument to `znap eval` is a repo and the repo's Git index is newer than the cache.
* If the last argument to `znap eval` has changed.

If we rewrite your call to `znap eval` slightly, then we can use this last case to regenerate the cache whenever the version of `direnv` has changed. The following should do the trick:
```zsh
znap eval asdf-direnv "asdf exec $(asdf which direnv) hook zsh"
```

I will update the Readme to mention this.

**Comment by marlonrichert** [comment]
Done.
