### ISSUE TITLE
Pure prompt initialization interference with iTerm shell integration

### ISSUE THREAD

**Issue by borekb** [marlonrichert/zsh-snap#134]
The README of this project [shows](https://github.com/marlonrichert/zsh-snap/blob/4a35a4b856e67cdcb13bd37f36fce3f20d34a83e/README.md?plain=1#L40-L41) this way to initialize the Pure prompt:

```zsh
# `znap prompt` makes your prompt visible in just 15-40ms!
znap prompt sindresorhus/pure
```

I've been using it this way, the full setup in my case being this:

```zsh
PURE_PROMPT_SYMBOL=$
git_color=green
PROMPT='%(?.%F{253}$.%F{red}$)%f '
znap prompt sindresorhus/pure
```

However, since relatively recently, I've been hitting issues with iTerm2 shell integration which is described here: https://gitlab.com/gnachman/iterm2/-/issues/9938

As a workaround / solution for me, I had to update my Pure prompt activation to look like this:

```diff
PURE_PROMPT_SYMBOL=$
git_color=green
PROMPT='%(?.%F{253}$.%F{red}$)%f '
znap prompt sindresorhus/pure
+prompt pure
```

This seems to fix the strange cmd-k issue for me but I have no idea why, or if my previous way to activate Pure was right or not. I've [documented this workaround in GitLab](https://gitlab.com/gnachman/iterm2/-/issues/9938#note_726629448).

I just wanted to report it in case it really was some kind of subtle issue with Znap (which I'm not sure at all!).

**Comment by marlonrichert** [comment]
This has nothing to do with Znap. I can reproduce it as follows:
```zsh
% cd $(mktemp -d)
% curl -L https://iterm2.com/shell_integration/zsh -o .iterm2_shell_integration.zsh
% git clone --depth 1 -- https://github.com/sindresorhus/pure.git
% > .zshrc <<EOF
fpath=( ./pure $fpath[@] )
autoload -Uz promptinit
promptinit
prompt pure
source .iterm2_shell_integration.zsh
EOF
% env -i HOME=$PWD PATH=$PATH FPATH=$FPATH TERM=$TERM zsh -d
% 
```
