### ISSUE TITLE
Feature request: it would be nice to have a Znap command to ask if a plugin is cloned

### ISSUE THREAD

**Issue by mattmc3** [marlonrichert/zsh-snap#14]
Maybe I'm thinking about this wrong and don't know the "znap way" of doing this, but currently I have code like this in my .zshrc:

```shell
if [[ ! -d $(znap path)/zsh-autosuggestions ]]; then
    znap clone zsh-users/zsh-autosuggestions
fi
znap source zsh-autosuggestions
```

It seems like that pattern might be better served with a convenience command within znap. One idea I had was adding an 'exists' subcommand.

```shell
if ! znap exists zsh-autosuggestions; then
    znap clone zsh-users/zsh-autosuggestions
fi
znap source zsh-autosuggestions
```

Another option would be to revamp the `znap ls` command to not actually `ls`, but return a list that can be properly stored in a list.

```shell
plugins=$(\ls $(znap path))
# or, if ls returned a simple list...
# plugins=$(znap ls)
if ! (($plugins[(Ie)zsh-autosuggestions])); then
    znap clone zsh-users/zsh-autosuggestions
fi
znap source zsh-autosuggestions
```

And, finally, perhaps an all-in-one-command would be another possibility:

```shell
# bundle does a clone if it has to, and sources the plugin
znap bundle zsh-users/zsh-autosuggestions
```

Is there a canonical znap way to accomplish what I'm doing, or is there a feature we can get added to znap to achieve this better?

**Comment by marlonrichert** [comment]
The canonical "Znap way" of doing this is to `znap clone` everything once on the command line only. 🙂

Why would you need to check in your `.zshrc` file whether you have installed a plugin?

**Comment by mattmc3** [comment]
I frequently log into new machines (Raspberry Pis, servers, virtual machines, etc.) and grab my dotfiles via git to setup my ZSH set up the way I prefer. I like having that all happen in one step. I also frequently switch branches in my ZSH config to experiment with new tools, and when I switch back to my main branch I prefer ZSH to self-heal by setting itself back up automatically without extra steps. Nearly every other ZSH plugin manager I've tried in the past (antibody, antigen, zgen, zplug, zinit) has this ability.

**Comment by marlonrichert** [comment]
All right, it's there now. If you now do `znap source zsh-users/zsh-autosuggestions` instead of `znap source zsh-autosuggestions`, it will automatically call `znap clone` with the same arguments, if there is no `zsh-autosuggestions` repo yet. This works for `znap prompt`, too.

**Comment by novirium** [comment]
Hi, just came across this while giving Znap a go: This feature appears to have been broken in a recent [commit](https://github.com/marlonrichert/zsh-snap/commit/10b5041a11fdaeec3ec0fce9b71bb406bd4f6176) - the call to `.znap.clone` is no longer receiving any arguments, I think `$1` is being cleared by the anonymous function added [here](https://github.com/marlonrichert/zsh-snap/blob/bb4dee47cd509ce47ce81fd1cbb639f1421b4b0e/functions/.znap.prompt#L48) and [here](https://github.com/marlonrichert/zsh-snap/blob/bb4dee47cd509ce47ce81fd1cbb639f1421b4b0e/functions/.znap.source#L14)?

**Comment by marlonrichert** [comment]
Whoops! Thanks for reporting. Should be fixed now.
