### ISSUE TITLE
znap pull - unknown option `quiet'

### ISSUE THREAD

**Issue by thepreacher** [marlonrichert/zsh-snap#140]
I just did `znap pull` this morning and got the following error message:

```
error: unknown option `quiet'
usage: git maintenance start [--scheduler=<scheduler>]

    --scheduler <scheduler>
                          scheduler to trigger git maintenance run
```
I'm using git version 2.34.0

**Comment by YenLegion** [comment]
Are you on WSL?

**Comment by thepreacher** [comment]
> Are you on WSL?

No I'm on macOS.

**Comment by marlonrichert** [comment]
Looks like starting with Git 2.34.0, [`git maintenance` no longer knows any other option than `--scheduler`](https://github.com/git/git/commit/eba1ba9d32f14dd9c052b1e2eb50e5718421d10e).
