### ISSUE TITLE
Can't use ohmyzsh/plugins/genpass

### ISSUE THREAD

**Issue by 343dev** [marlonrichert/zsh-snap#147]
Hi.
Thanks for this great plugin manager for Zsh!
I migrated from Antigen and configured almost everything I needed, but couldn't get the [genpass](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/genpass) plugin from [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh) to work.

I have this line in .zshrc to connect plugins:
```
znap source ohmyzsh/ohmyzsh plugins/{bgnotify,colored-man-pages,genpass,sublime}
```

Then, when I try to call one of the commands, such as `genpass-apple`, I get an error:
```
zsh: genpass-apple: function definition file not found
```

Perhaps I need to connect this plugin in some other way? 🤔

**Comment by marlonrichert** [comment]
Hm, you have there an edge case that I haven’t seen before. I will need to consider how to solve this in an elegant way. 🤔

In the meantime, this should do the trick:
```zsh
autoload -Uz ~[ohmyzsh/ohmyzsh]/plugins/genpass/*
```

**Comment by 343dev** [comment]
> In the meantime, this should do the trick:

Thanks.

**Comment by marlonrichert** [comment]
@343dev I solved it as follows:
* Use `znap install ohmyzsh/ohmyzsh` on the command line to install the functions bundled with OMZ.
* In your `.zshrc` file:
  * Remove `genpass` from `znap source`.
  * Instead, use `autoload -Uz <function> ...` to enable the functions you need. So, if you need only `genpass apple`, add `autoload -Uz genpass-apple`. If you need all three functions, add `autoload -Uz genpass-{apple,monkey,xkcd}`.

**Comment by 343dev** [comment]
> @343dev I solved it as follows:

I updated zsh-snap and followed your instructions, but I still get the same error:

```
zsh: genpass-apple: function definition file not found
```

🤷

**Comment by marlonrichert** [comment]
Have you updated Znap to the latest version? Dis you restart your shell?

**Comment by 343dev** [comment]
I ran `znap pull` and removed the line `znap source ohmyzsh/ohmyzsh plugins/genpass` from the .zshrc.

Then I ran `znap install ohmyzsh/ohmyzsh`, restarted the shell, and ran `autoload -Uz genpass-apple`.

Still no luck. Maybe I miss something?

**Comment by marlonrichert** [comment]
Whoops, I wasn't expecting these function files to be executable (because that doesn't make any sense, but whatever). Should be fixed now! 🙂 

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 💝

**Comment by 343dev** [comment]
Thanks, now it works 👍
