### ISSUE TITLE
No way to install a subset of zsh completions

### ISSUE THREAD

**Issue by optix2000** [marlonrichert/zsh-snap#148]
Today you can install _all_ completions using `znap install ohmyzsh/ohmyzsh`. I didn't see a way in the readme or `znap help` to install only a single completion from a repo.

For example if you want to install only the ripgrep completion from ohmyzsh, running `znap install ohmyzsh/ohmyzsh plugins/ripgrep` will try to clone `plugins/ripgrep`, instead of installing _only_ the docker completion.

Having a way to install a selection of completions would allow mixing and matching completions from different repos and places.

**Comment by marlonrichert** [comment]
> running `znap install ohmyzsh/ohmyzsh plugins/ripgrep` will try to clone `plugins/ripgrep`, instead of installing _only_ the docker completion.

The syntax for `znap install` is different from that of `znap source`. Whereas `znap source` allows you to specify exactly which files or modules to source from a particular repo, `znap install` instead lets you install multiple repos in parallel. It currently does not let you pick exactly what to install.

However, there is no harm in installing multiple completions. They won't actually be loaded unless you try to use them. 🙂
