### ISSUE TITLE
Cursor not visible in Terminal.app on MacOS when running znap prompt

### ISSUE THREAD

**Issue by mattmc3** [marlonrichert/zsh-snap#15]
When running `znap prompt pure` from .zshrc, the cursor starts out invisible. I have tried with multiple prompts with the same result:
- sindresorhus/pure
- miekg/lean
 - agnoster/agnoster-zsh-theme
 - romkatv/powerlevel10k

If I run `reset` or call `.znap.prompt.echoti cnorm` manually in the terminal, the cursor then shows up.

----------------------------------
Diagnostics:

znap version: Latest

```shell
$ zsh --version                
zsh 5.8 (arm-apple-darwin20.1.0)
```

MacOS version: 11.1

**Comment by marlonrichert** [comment]
I'm on macOS 11.1 (20C69), Terminal.app 2.11 (440), Zsh 5.8 (x86_64-apple-darwin19.3.0), and I cannot reproduce this. Here's what I tried:
 1. Create and enter a temp dir:
    ```zsh
    % cd $(mktemp -d)
    ````
 2. Create a file `.zshrc` there with the following contents:
    ```zsh
    source /Users/marlon/.zsh/zsh-snap/znap.zsh
    znap prompt pure
    ```
 3. Start a subshell there without global config files:
    ```
    % HOME=$PWD ZDOTDIR=$PWD zsh -d
    ```

Works fine for for me. Can you pleas try the exact steps above and see if it works for you? If it does, then there must be something else going on in your shell.

**Comment by mattmc3** [comment]
Thanks for this. I was able to try the steps you detail and can confirm that the cursor works. So, I began adding plugins back to see if I could find the conflict and determined that it's from oh-my-zsh.

if I `znap source ohmyzsh` (or even just `source $ZSH/oh-my-zsh.sh`) **after** running `znap prompt pure`, the cursor is gone. However, if I `znap source ohmyzsh` **before** running `znap prompt pure`, things work properly.

Let me know if you see the same thing with this .zshrc:

```
# if this is before OMZ, the cursor is gone
znap prompt pure

# use omz plugin
znap source ohmyzsh

# alternately, source OMZ yourself... same result
# ZSH=$(znap path)/ohmyzsh
# source $ZSH/oh-my-zsh.sh
```

I'm not sure this is something wrong with znap or something with the way OMZ works. But, since oh-my-zsh is a pretty common plugin, it might be worth at least adding to the docs that you have to source it before setting up the prompt. Unfortunately, that solution might negate all the speed you get from having an instant prompt since OMZ is likely to be the slowest part of loading, so doing it after isn't ideal. Anyway, thanks for looking into it.

**Comment by mattmc3** [comment]
Looks like it's not just oh-my-zsh - prezto does this too. It's in the keybindings of these frameworks:

```shell
# omz's key-bindings causes the cursor to be missing
znap source ohmyzsh lib/key-bindings

# prezto also causes cursor to be missing
znap source prezto modules/editor
```

**Comment by marlonrichert** [comment]
Thanks for the detailed info! I’ll see if I can work around it.

**Comment by marlonrichert** [comment]
Fixed.
