### ISSUE TITLE
Installing as Brew Package?

### ISSUE THREAD

**Issue by ChristopherA** [marlonrichert/zsh-snap#150]
Would you consider offering this (and maybe launchpad) as a `brew` plugin? I like the " 'tween the easy to bootstrap &  developer springboard" philosophy of these, but all of my macos and debian new machine install scripts use `brew` now. `zinit` has a brew package, but feels far too complex.

**Comment by marlonrichert** [comment]
I’ll do it if someone pays me for it. 😉

Otherwise, please see my answer to the same question over here: https://github.com/marlonrichert/zsh-autocomplete/issues/379#issuecomment-986000768
