### ISSUE TITLE
znap auto-compiling feature

### ISSUE THREAD

**Issue by anuvyklack** [marlonrichert/zsh-snap#156]
1. After last update, to be precise, after 6e5c038aab1887a97eae0882e7372f41ff911aaf commit, the next line:

   ```zsh
   zstyle ':znap:*' auto-compile-ignore "${my_zsh_functions}/*"
   ```

   spawns a 1 thread 100% cpu zsh process after quitting shell.
   
   As I see, the instruction about this command has gone from the README, and it will be better to place the message about its deprecation somewhere into changelog.

2. The problem is that on the last commit `znap` stops auto-compiling any files.
   I don't set `zstyle ':znap:*' auto-compile no`.

**Comment by marlonrichert** [comment]
I'm unable to reproduce either of these problems. Can you please add a reproducible test case?

> As I see, the instruction about this command has gone from the README, and it will be better to place the message about its deprecation somewhere into changelog.

It's not deprecated; I just don't want to advertise it.

**Comment by marlonrichert** [comment]
See also #158

**Comment by AliTajelsir** [comment]
> The problem is that on the last commit znap stops auto-compiling any files.
I don't set zstyle ':znap:*' auto-compile no.

I'm facing the same issue.

**Comment by marlonrichert** [comment]
@anuvyklack @AliTajelsir I'm still unable to reproduce this. Can you please provide me with a minimal reproducible test case?

**Comment by marlonrichert** [comment]
@AliTajelsir Are all three plugins actually necessary for this test? Can you reproduce it without them?

> No auto-compiling

How do you know? Can you please include your steps for testing this?

**Comment by AliTajelsir** [comment]
- Sorry, they aren't necessary. Just for example. Only `znap` suffice:
  ```
  [ -f $XDG_DATA_HOME/znap/zsh-snap/znap.zsh ] ||
	  git clone https://github.com/marlonrichert/zsh-snap.git $XDG_DATA_HOME/znap/zsh-snap/
  source $XDG_DATA_HOME/znap/zsh-snap/znap.zsh
```
- My testing is very primitive. I just check for the creation for `.zwc` files e.g. `.zshrc.zwc`
- Sorry for the confusion. If I'm doing it wrong, what should I do?

**Comment by marlonrichert** [comment]
> My testing is very primitive. I just check for the creation for `.zwc` files e.g. `.zshrc.zwc`

Currently, Znap auto-compiles only those files that contain function definitions (plus a couple of specific files that are known to produce performance gains when compiled, such as the comp dump). If your `.zshrc` itself doesn’t define any functions, it won’t be compiled. This is intentional.
