### ISSUE TITLE
zsh-auto-suggestions plugin doesn't appear at the first start

### ISSUE THREAD

**Issue by marlonrichert** [marlonrichert/zsh-snap#159]
### Discussed in https://github.com/marlonrichert/zsh-snap/discussions/157

<div type='discussions-op-text'>

<sup>Originally posted by **vpeopleonatank** December 23, 2021</sup>
Everytime I open new zsh shell session, this plugin doesn't appear immediately, I need to press `Ctrl+c` or execute some command such as `ls` to make it run normally. How can I make this plugin run at the first start?

Here is my minimal zshrc
```
if [ ! -d "$HOME/.zsh/zsh-snap"  ]; then
    git clone --depth 1 https://github.com/marlonrichert/zsh-snap.git $HOME/.zsh/zsh-snap
fi
source $HOME/.zsh/zsh-snap/znap.zsh

znap source romkatv/powerlevel10k
znap source jeffreytse/zsh-vi-mode
function zvm_after_init() {
  ZSH_AUTOSUGGEST_STRATEGY=( history  )
  znap source zsh-users/zsh-autosuggestions  # On same line
  export ZSH_AUTO_SUGGEST_USE_ASYNC=true
}
 
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

HISTFILE=~/.zsh_history
HISTSIZE=999999999
SAVEHIST=$HISTSIZE
setopt SHARE_HISTORY
```

</div>

**Comment by marlonrichert** [comment]
@vpeopleonatank What happens if you remove P10k from there? Do you still experience the same problem?

**Comment by vpeopleonatank** [comment]
After removing P10k, the problem still occurs.
But put `zsh-autosuggestions` plugin out of zvm_after_init() function, this issue is solved
Here is my minimal working zshrc
```
if [ ! -d "$HOME/.zsh/zsh-snap"  ]; then
    git clone --depth 1 https://github.com/marlonrichert/zsh-snap.git $HOME/.zsh/zsh-snap
fi
source $HOME/.zsh/zsh-snap/znap.zsh

znap source jeffreytse/zsh-vi-mode
function zvm_after_init() {
  ZSH_AUTOSUGGEST_STRATEGY=( history  )
  export ZSH_AUTO_SUGGEST_USE_ASYNC=true
}
 
znap source zsh-users/zsh-autosuggestions 

HISTFILE=~/.zsh_history
HISTSIZE=999999999
SAVEHIST=$HISTSIZE
setopt SHARE_HISTORY
```
