### ISSUE TITLE
Feature request: Add zstyle configuration option for excluding znap compile paths

### ISSUE THREAD

**Issue by mattmc3** [marlonrichert/zsh-snap#16]
I am really loving znap - this is such a great project! I can finally ditch antibody (which is go based and doesn't work on the new M1 Macs yet.) Thanks for all your work on it.

One thing I'm running into that I would love to see a feature for is more fine grained control of what gets zcompiled. Specifically, it would be really nice to be able to exclude directories. Having a .zwc file cached can cause subtle issues in your ZSH configuration when you are making changes.

Right now, znap takes an all-or-nothing approach to compiling with the `zstyle ':znap:*' auto-compile no` setting. I would love to see an optional zstyle setting like "auto-compile-exclude-dirs" that would add directories to a block list that znap compile would ignore. That way you could do something like this to protect some more volatile directories in your ZSH config, but still get the benefits of having the more static plugin code compiled:

```shell
zstyle ':znap:*' auto-compile-exclude-dirs ${ZDOTDIR:-$HOME}/.zshrc.d ${ZDOTDIR:-$HOME}/zfunctions
```

Thanks for considering!

**Comment by marlonrichert** [comment]
Done.
