### ISSUE TITLE
`znap pull` exits with return code 1

### ISSUE THREAD

**Issue by marlonrichert** [marlonrichert/zsh-snap#162]
### Discussed in https://github.com/marlonrichert/zsh-snap/discussions/161

<div type='discussions-op-text'>

<sup>Originally posted by **thepreacher** January  4, 2022</sup>
Every time I run `znap-pull` it exits with return code `1` and my prompt goes from green to red. I've looked at the code in [.znap-pull](https://github.com/marlonrichert/zsh-snap/blob/main/functions/.znap.pull) and to this piece of code:

```zsh
    if ! git diff --quiet @; then
      print -P '%F{red}dirty%f'
      return 1
    fi
```
I've not touched any of the packages that I'm using so I'm not sure why there would be difference between any local package and it's remote counterpart. I'll like to know exactly which package is causing this. Any help?</div>

**Comment by marlonrichert** [comment]
@thepreacher Thanks for reporting. I can confirm that `znap pull` indeef mistakenly exits with a non-zero exit code. I will fix this.

However, the code you pasted has nothing to do with it. 🙂

**Comment by thepreacher** [comment]
> However, the code you pasted has nothing to do with it. 🙂
@marlonrichert :laughing: Here I was feeling smug that I've nailed the culprit.
