### ISSUE TITLE
`znap install` doesn't install executables to `~/.local/bin`

### ISSUE THREAD

**Issue by anuvyklack** [marlonrichert/zsh-snap#166]
As said in the title. None of the next lines doesn't install executables to `~/.local/bin` how it was in the past.
```
znap install anuvyklack/vifmimg
znap install anuvyklack/vifmpane
znap install xwmx/nb
```

</details>

## Environment:
 - OS: Ubuntu 21.10
 - Terminal: kitty 0.24.2
 - Zsh version: 5.8
 - Repo version: aa8396a

**Comment by anuvyklack** [comment]
b95221a8b0cae33c056e7caefc9a4037568dc8a3 is the first bad commit

**Comment by marlonrichert** [comment]
@anuvyklack Thanks for identifying the commit! However, I don’t have time at the moment to fix it myself. Patches welcome!

**Comment by marlonrichert** [comment]
@anuvyklack @pdufour @kuator Fixed! 🙂 

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 💝
