### ISSUE TITLE
cannot turn of git-maintenance

### ISSUE THREAD

**Issue by tshu-w** [marlonrichert/zsh-snap#169]
## Describe the bug
I cannot turn of git-maintenance by `zstyle ':znap:*:*' git-maintenance off`

## Steps To Reproduce

```zsh
### zshrc
# ZNAP_HOME=$XDG_DATA_HOME/zsh/zsh-snap
# if [[ ! -f $ZNAP_HOME/znap.zsh ]]; then
#     git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git $ZNAP_HOME
# fi
# zstyle ':znap:*:*' git-maintenance off
# source $ZNAP_HOME/znap.zsh
# unset ZNAP_HOME
znap pull
```

## Expected behavior
znap maintenance feature was disabled.

## Observed behavior
git maintenance show after `znap pull`.

## Environment:
 - OS: macOS
 - Terminal: iterm
 - Zsh version: 5.8
 - Repo version: aa8396a

**Comment by marlonrichert** [comment]
I'm unable to reproduce this.

**Comment by tshu-w** [comment]
Sorry, it works in recent version and I don't know why.
