### ISSUE TITLE
znap clone command not cloning repos for me anymore

### ISSUE THREAD

**Issue by thepreacher** [marlonrichert/zsh-snap#17]
Today I tried to clone a repo `https://github.com/dmy/elm-sh-completion.git` with the commands `znap clone https://github.com/dmy/elm-sh-completion.git` and later with `znap clone git@github.com:/dmy/elm-sh-completion.git` when first one didn't work, but although the command seems to fininsh successfully, the repo is not acutally cloned. However an entry is added to `~/.config/zsh/znap-repos`

I am able to successfully clone the repo with `git clone https://github.com/dmy/elm-sh-completion.git` however.

An as aside when `znap rm <repo>` finishes, the entry for `<repo>` in znap-repos is not removed.

**Comment by marlonrichert** [comment]
Hm, you're right: `znap clone` appears to be broken. I'll investigate.

> An as aside when `znap rm <repo>` finishes, the entry for `<repo>` in znap-repos is not removed.

That is entirely intentional. I have been on the fence about it. I might change it. Not sure.

**Comment by marlonrichert** [comment]
`znap clone` should be fixed now. I'll have to think about the `znap rm` behavior.

**Comment by marlonrichert** [comment]
`znap rm` now asks if you want to remove the repo entry from `znap-repos`.
