### ISSUE TITLE
/etc/grc.zsh:86: cmd: attempt to assign private in nested scope

### ISSUE THREAD

**Issue by whoizit** [marlonrichert/zsh-snap#171]
```
znap source ohmyzsh/ohmyzsh \
  lib/{diagnostics,completion,git} \
  plugins/{command-not-found,colored-man-pages,grc,branch,zoxide,asdf,git,mercurial,rust,flutter}
```
## Steps To Reproduce

```zsh

```

## Observed behavior

<details><summary>Click to expand</summary>

</details>

## Environment:
 - OS: ArtixLinux 
 - Terminal: foot 
 - Zsh version: zsh 5.8.1 
 - Repo version: * main aa8396a Support prompt themes that don't have a repo

**Comment by marlonrichert** [comment]
Unable to reproduce
