### ISSUE TITLE
How to uninstall znap?

### ISSUE THREAD

**Issue by ibehnam** [marlonrichert/zsh-snap#177]
[this](https://github.com/marlonrichert/zsh-snap/issues/85#issue-931325957) was closed before without providing an answer. How should we remove/uninstall znap?

**Comment by marlonrichert** [comment]
Sorry about closing and locking that issue. I'm not sure what happened there. I've reopened it now.

**Comment by NanguRepo** [comment]
what happened here? did he get his answer?

**Comment by behnamoh** [comment]
I didn’t, but I followed the following and just deleted the folder. 

https://github.com/marlonrichert/zsh-snap/discussions/124
