### ISSUE TITLE
eval command run inside wrong dir

### ISSUE THREAD

**Issue by mnowotnik** [marlonrichert/zsh-snap#182]
## Describe the bug

According to the example .zshrc `eval` command :
> \# If the first arg is a repo, then the command will run inside it.
> znap eval trapd00r/LS_COLORS "$( whence -a dircolors gdircolors ) -b LS_COLORS"

Yet command gets run inside $HOME directory

`  znap eval some/repo "printf 'echo $PWD'"`

## Steps To Reproduce

```zsh
znap eval some/repo "printf 'echo $PWD'"
```

## Expected behavior

`znap eval` should be run inside repository or the documentation should be changed.
Is there any way to run initialization scripts inside plugins' repositories?

## Environment:
 - OS: Linux
 - Terminal: Tilix
 - Zsh version: 5.8.1
 - Repo version: `main b2365b1`

**Comment by marlonrichert** [comment]
> ```zsh
> znap eval some/repo "printf 'echo $PWD'"
> ```

The problem is with your command: In `"printf 'echo $PWD'"`, `$PWD` gets evaluated _immediately,_ because the string is wrapped in double quotes. Try this instead:
```zsh
znap eval some/repo 'printf "echo $PWD"'
```
