### ISSUE TITLE
Not sure, maybe a typo

### ISSUE THREAD

**Issue by sidkang** [marlonrichert/zsh-snap#185]
https://github.com/marlonrichert/zsh-snap/blob/de2e7c684b0a2cf6b6f5a160927a74511475a515/README.md?plain=1#L51-L53

Just found in the sample config in README, there is a `pyenvn`, is this a typo? It's different from the `.zshrc` file.

**Comment by marlonrichert** [comment]
Yep, that’s a typo. Thanks!
