### ISSUE TITLE
Current path not correctly display in zsh-snap parent folder

### ISSUE THREAD

**Issue by MartinDelille** [marlonrichert/zsh-snap#188]
## Describe the bug

I cloned `zsh-snzp` in the `~/dev/clone` folder. Unfortunately, when I'm navigating to this folder the part of the prompt display `~znap` instead of `~/dev/clone`.

## Steps To Reproduce

```zsh
Last login: Sat Aug 27 15:38:30 on ttys010
{15:38}[ruby-2.7.2]~ ➭ cd dev/clone/zsh-snap
{15:39}[ruby-2.7.2]~[zsh-snap]:main ✓ ➭ cd ..
{15:39}[ruby-2.7.2]~znap ➭ cd ~/dev/clone
{15:39}[ruby-2.7.2]~znap ➭ cd
{15:39}[ruby-2.7.2]~ ➭ cd dev
{15:39}[ruby-2.7.2]~/dev ➭ cd clone
{15:39}[ruby-2.7.2]~znap ➭ cd ../md
{15:40}[ruby-2.7.2]~/dev/md ➭
```

## Expected behavior

```
{15:43}[ruby-2.7.2]~ ➭ cd ~/dev/clone
{15:43}[ruby-2.7.2]~/dev/clone ➭
```

## Observed behavior

<details><summary>Click to expand</summary>

</details>

## Environment:
 - OS: macOS
 - Terminal: iTerm
 - Zsh version: 5.7.1
 - Repo version: 
   - main c0fa1da Let `znap source` store plugin links in `$XDG_STATE_HOME`

**Comment by MartinDelille** [comment]
Ok looking at the README.md it has to do with [named dirs](https://github.com/marlonrichert/zsh-snap#named-dirs)

**Comment by marlonrichert** [comment]
It’s expected behavior, as documented in the part of the Readme that you linked to.
