### ISSUE TITLE
Shell welcome message being cleared by prompt

### ISSUE THREAD

**Issue by neolee** [marlonrichert/zsh-snap#191]
## Describe the bug
If I print some welcome message in my `.zshrc`, and use `znap prompt xxx` to load some prompt theme, then the the welcome message will be cleared while prompt loaded.

## Steps To Reproduce
Code snippet in my `.zshrc`:
```zsh
source $HOME/.znap/zsh-snap/znap.zsh
...
znap prompt sindresorhus/pure

znap source marlonrichert/zsh-autocomplete
znap source marlonrichert/zsh-edit
znap source marlonrichert/zsh-hist
...
echo "Welcome to the REAL world!\n"
```
When shell started, it will display the welcome message a very short while then disappear while the pure prompt popping out.

## Expected behavior
I wanna to keep my welcome message. So what can I do? Or how can I run some code **after** prompt theme fully loaded?

</details>

## Environment:
 - OS: macOS
 - Terminal: iTerm 2
 - Zsh version: zsh 5.9 (arm-apple-darwin21.3.0)
 - Repo version: main c0fa1da

**Comment by marlonrichert** [comment]
> Or how can I run some code after prompt theme fully loaded?

```zsh
autoload -Uz add-zsh-hook

add-zsh-hook precmd message-hook
message-hook() {
  add-zsh-hook -d precmd message-hook # Delete the hook.

  zmodload -F zsh/terminfo b:echoti   # Load echoti builtin.
  echoti el                           # Clear to end of line.
  print 'message'

  unfunction message-hook
} 
```

**Comment by neolee** [comment]
Thanks @marlonrichert ! The hook method is perfect solution. Close the issue.
