### ISSUE TITLE
znap breaks zsh's nohup settings

### ISSUE THREAD

**Issue by ppwwyyxx** [marlonrichert/zsh-snap#193]
## Describe the bug
Sourcing znap invalidates my zsh's `unsetopt hup` setting.

## Steps To Reproduce
Have the following in my `.zshrc`:
```zsh
unsetopt hup
source ~/.zsh/snap/zsh-snap/znap.zsh
```
And then the first line has no effect. Background jobs still get terminated as long as the shell exits.

If I swap the two lines, then `unsetopt hup` is effective.

## Expected behavior
I expect znap to not mess with this setting.

## Environment:
 - OS: ubuntu
 - Terminal: alacritty
 - Zsh version: 5.9
 - Repo version: eef4b19 Let `git pull` decide how many parallel processes to use

**Comment by marlonrichert** [comment]
Znap resets all settings on this line: https://github.com/marlonrichert/zsh-snap/blob/eef4b19e6797712d9cc153e8bb2075e12d3c9fdb/znap.zsh#L2

However, I don’t really see a clear need for this anymore. It can be removed. Do you want to submit a pull request with this change? 🙂

**Comment by ppwwyyxx** [comment]
Thanks for the response. Sent #194.
