### ISSUE TITLE
`init.zsh:zf_ln:62: /.zsh/zsh-snap/functions/_znap: file exists`

### ISSUE THREAD

**Issue by Stanzilla** [marlonrichert/zsh-snap#196]
Hey there, I'm not sure if this is a bug or a configuration issue on my side but I've been getting this issue for a while, when I open up my terminal: `init.zsh:zf_ln:62: /home/stan/.zsh/zsh-snap/functions/_znap: file exists`

zsh is running in a WSL v2 VM here.

**Comment by marlonrichert** [comment]
Which version of Zsh do you use?

**Comment by Stanzilla** [comment]
> Which version of Zsh do you use?

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

**Comment by marlonrichert** [comment]
Can you try the following?
```zsh
cd $( mktemp -d )
zmodload -F zsh/files b:zf_ln 
zf_ln -fhs .. foo
ls -lAF
zf_ln -fhs . foo
ls -lAF
ln -fhs .. foo
ls -lAF
```
What output do you get?

**Comment by Stanzilla** [comment]
> Can you try the following?
> 
> ```shell
> cd $( mktemp -d )
> zmodload -F zsh/files b:zf_ln 
> zf_ln -fhs .. foo
> ls -lAF
> zf_ln -fhs . foo
> ls -lAF
> ln -fhs .. foo
> ls -lAF
> ```
> 
> What output do you get?

That looks like it was my mistake, aliasing ls to exa, haha


> ❯ cd $( mktemp -d )
> zmodload -F zsh/files b:zf_ln
> zf_ln -fhs .. foo
> ls -lAF
> zf_ln -fhs . foo
> ls -lAF
> ln -fhs .. foo
> ls -lAF
> exa: Unknown argument -A
> exa: Unknown argument -A
> ln: invalid option -- 'h'
> Try 'ln --help' for more information.
> exa: Unknown argument -A

**Comment by marlonrichert** [comment]
That doesn't explain the original linking error, though. Can you please do `unalias ls` and then try again?

**Comment by Stanzilla** [comment]
> That doesn't explain the original linking error, though. Can you please do `unalias ls` and then try again?

> /tmp/tmp.tqykKFke4a
> ❯ unalias ls
> 
> /tmp/tmp.tqykKFke4a
> ❯ cd $( mktemp -d )
> zmodload -F zsh/files b:zf_ln
> zf_ln -fhs .. foo
> ls -lAF
> zf_ln -fhs . foo
> ls -lAF
> ln -fhs .. foo
> ls -lAF
> total 0
> lrwxrwxrwx 1 stan stan 2 Oct 25 16:47 foo -> ../
> total 0
> lrwxrwxrwx 1 stan stan 1 Oct 25 16:47 foo -> ./
> ln: invalid option -- 'h'
> Try 'ln --help' for more information.
> total 0
> lrwxrwxrwx 1 stan stan 1 Oct 25 16:47 foo -> ./

**Comment by marlonrichert** [comment]
OK, then I have no idea why this is failing for you on startup. Which version of Znap do you use?

**Comment by Stanzilla** [comment]
Up to date with main atm

**Comment by marlonrichert** [comment]
Can you share your `.zshrc` file?

**Comment by Stanzilla** [comment]
> Can you share your `.zshrc` file?

>>> #!/usr/bin/env zsh
# shellcheck shell=bash
# shellcheck disable=SC1090 # sourced filenames with variables
# shellcheck disable=SC2034 # unused variables

source ~/.zsh/zsh-snap/znap.zsh

PATH=$PATH:$HOME/.local/bin
export PATH="/usr/local/sbin:$PATH"
export GPG_TTY=$(tty)

znap prompt sindresorhus/pure

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 10240 lines of history within the shell and save it to ~/.zsh_history:
HISTFILE=~/.zsh_history
HISTSIZE=10240
SAVEHIST=10240

history_ignore=(
    'history'
    'env'
    'll',
    'ls'
    'ls -lha'
    'ls -1'
    'cd ..'
    'cd -'
    'clear'
    'pwd'
    'exit'
    'date'
    '* --help'
    'op'
    'op *'
    'pass'
    'pass *'
    'pony'
    'pony *'
)

HISTORY_IGNORE="(${(j.|.)history_ignore})"
DISABLE_AUTO_TITLE="true"

function precmd() {
    window_title="\033]0;${PWD##*/}\007"
    echo -ne "$window_title"
}

autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic

autoload -Uz bracketed-paste-url-magic
zle -N bracketed-paste bracketed-paste-url-magic

# forces zsh to realize new commands
zstyle ':completion:*' completer _oldlist _expand _complete _match _ignored _approximate

# matches case insensitive for lowercase
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# pasting with tabs doesn't perform completion
zstyle ':completion:*' insert-tab pending

# rehash if command not found (possibly recently installed)
zstyle ':completion:*' rehash true

# menu if nb items > 2
zstyle ':completion:*' menu select=2

# kill complete
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# starting letter highlight
zstyle -e ':completion:*:default' list-colors 'reply=("${PREFIX:+=(#bi)($PREFIX:t)(?)*==34=34}:${(s.:.)LS_COLORS}")';

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"

alias reload='exec "$SHELL" -l'
alias ls="exa --group-directories-first"
alias ll="exa --group-directories-first -alh"
alias tree="exa --tree --level=3"
alias cat="bat -p"
alias config="code ~/.zshrc"
alias npi="npm install"
alias npa="npm audit fix"
alias npb="npm run build"
alias npd="npm run dist"

# Colormap
function colormap() {
  for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done
}

znap source lukechilds/zsh-better-npm-completion
znap source sindresorhus/pretty-time-zsh
znap source Tarrasch/zsh-bd
znap source caarlos0/git-add-remote
znap source caarlos0/zsh-mkc

znap source zsh-users/zsh-completions
znap source zsh-users/zsh-autosuggestions

# these should be last!
znap source mafredri/zsh-async
znap source zdharma-continuum/fast-syntax-highlighting
znap source zsh-users/zsh-history-substring-search
znap source unixorn/fzf-zsh-plugin

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

/usr/bin/keychain --nogui --quiet "$HOME"/.ssh/id_rsa
/usr/bin/keychain --nogui --quiet "$HOME"/.ssh/id_rsa_gmail
/usr/bin/keychain --nogui --quiet "$HOME"/.ssh/id_rsa_manticore
source "$HOME"/.keychain/"$HOST"-sh

bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

### ctrl + arrows
bindkey "\e[1;5C" forward-word
bindkey "\e[1;5D" backward-word

### ctrl + delete
bindkey "\e[3;5~" kill-word

### ctrl + backspace
bindkey "^H" backward-kill-word

### ctrl + shift + delete
bindkey "\e[3;6~" kill-line

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# Options to fzf command
export FZF_COMPLETION_OPTS='--border --info=inline'
export FZF_PREVIEW_ADVANCED=true

# Use fd (https://github.com/sharkdp/fd) instead of the default find
# command for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Use fd and fzf to get the args to a command.
# Works only with zsh
# Examples:
# f mv # To move files. You can write the destination after selecting the files.
# f 'echo Selected:'
# f 'echo Selected music:' --extension mp3
# fm rm # To rm files in current directory
f() {
  sels=( "${(@f)$(fd "${fd_default[@]}" "${@:2}"| fzf)}" )
  test -n "$sels" && print -z -- "$1 ${sels[@]:q:q}"
}

# Like f, but not recursive.
fm() f "$@" --max-depth 1

# Deps
alias fz="fzf-noempty --bind 'tab:toggle,shift-tab:toggle+beginning-of-line+kill-line,ctrl-j:toggle+beginning-of-line+kill-line,ctrl-t:top' --color=light -1 -m"
fzf-noempty () {
  local in="$(</dev/stdin)"
  test -z "$in" && (
    exit 130
  ) || {
    ec "$in" | fzf "$@"
  }
}
ec () {
  if [[ -n $ZSH_VERSION ]]
  then
    print -r -- "$@"
  else
    echo -E -- "$@"
  fi
}

# Emit OSC 9;9 sequences to inform the terminal about the shell's working directory
__wt_osc9_9 () {
    _win_path=$(wslpath -m $(pwd))
    printf "\033]9;9;%s\033\\" "$_win_path"
}

[ -n "$BASH_VERSION" ] && [ -n "$WT_SESSION" ] && PROMPT_COMMAND="__wt_osc9_9"
[ -n "$ZSH_VERSION"  ] && [ -n "$WT_SESSION" ] && precmd_functions+=(__wt_osc9_9)

**Comment by marlonrichert** [comment]
I see nothing weird in your `.zshrc` and we haven’t been able to reproduce it on your machine with the test case I gave you. So, sorry, I don’t see anything I can do about this. 🙁
