### ISSUE TITLE
How would one use zsh-snap to install and configure powerlevel10k prompt

### ISSUE THREAD

**Issue by thepreacher** [marlonrichert/zsh-snap#2]
Thanks for your package. I was shocked when I saw how little code there actually was in your source file. I feel like with time I can come to understand it completely. 

I use **powerlevel10K** for my prompt with **antibody** and I'm considering trying out your pluggin manager however I'm not sure how to configure **powerlevel10K**  in my `.zshrc` seeing that it's got a bit more to its configuration than **pure prompt**.

**Comment by marlonrichert** [comment]
Run the following:
```zsh
znap clone https://github.com/romkatv/powerlevel10k.git
echo 'znap source powerlevel10k' >> ~/.zshrc
```
Then restart your shell.
