### ISSUE TITLE
Feature request: Give priority to .plugin.zsh files when sourcing for OMZ compatibility

### ISSUE THREAD

**Issue by novirium** [marlonrichert/zsh-snap#20]
Some OMZ plugins have multiple files ending in `.zsh`, and Znap currently just uses the first if a specific one isn't given. The OMZ framework uses the `.plugin.zsh` extension to indicate which file actually needs to be sourced to run the plugin, for instance in their bundled copy of [history-substring-search](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/history-substring-search).

When automatically finding a file to source, would Znap be able to prioritise `.plugin.zsh` files over plain `.zsh`? This would improve compatibility with OMZ plugins, and as far as I can tell wouldn't break the existing behaviour with other frameworks like Prezto.

**Comment by marlonrichert** [comment]
Done.
