### ISSUE TITLE
cursor not visible if starship prompt loaded before vi-mode

### ISSUE THREAD

**Issue by zdufour-asp** [marlonrichert/zsh-snap#201]
## Describe the bug

This seems to be a reocurrence of #15 , except this time my cursor disappears when `zsh-vi-mode` is `znap source`ed if-and-only-if I've already loaded my starship prompt

## Steps To Reproduce

cursor disappears if I load starship first:

```zsh
# `znap prompt` makes your prompt visible in just 15-40ms!
znap eval starship "starship init zsh --print-full-init"
znap prompt

znap source jeffreytse/zsh-vi-mode
```

cursor stays if I source `zsh-vi-mode` first

```zsh
znap source jeffreytse/zsh-vi-mode

# `znap prompt` makes your prompt visible in just 15-40ms!
znap eval starship "starship init zsh --print-full-init"
znap prompt
```

## Expected behavior

"should" be able to `znap prompt` before `znap source ...vi-mode` without disappearing my cursor. That being said, this seems like a game of whackamole, so I'm mostly creating this issue in case someone else runs into this and can find the workaround :)

## Observed behavior

cursor disappears

## Environment:
 - OS: macos
 - Terminal: kitty, tabby
 - Zsh version: `zsh --version` returns `zsh 5.8.1 (x86_64-apple-darwin21.0)`
 - Repo version: `main eef4b19`

**Comment by marlonrichert** [comment]
What happens if you do this instead?
```zsh
eval "$( starship init zsh --print-full-init )"
source /path/to/jeffreytse/zsh-vi-mode/zsh-vi-mode.plugin.zsh
```

Does the cursor disappear then, too?

**Comment by zdufour-asp** [comment]
No, then the cursor is still visible

**Comment by niksingh710** [comment]
is there any update or a fix on this ?

**Comment by marlonrichert** [comment]
I'm able to reproduce it with just
```zsh
znap prompt
znap source jeffreytse/zsh-vi-mode
```
So, the problem is not in Starship prompt. I'll investigate further.

**Comment by marlonrichert** [comment]
It's a bug in `jeffreytse/zsh-vi-mode`:

https://github.com/jeffreytse/zsh-vi-mode/blob/2f68ea900b73b9d8f76db70ee20ce65fd7678106/zsh-vi-mode.zsh#L3261
https://github.com/jeffreytse/zsh-vi-mode/blob/2f68ea900b73b9d8f76db70ee20ce65fd7678106/zsh-vi-mode.zsh#L374

They should _not_ redefine any of the `zle-` widgets. That can lead to all kinds of problems when other plugins use these, too. Instead, they should [`add-zle-hook-widget`](https://zsh.sourceforge.io/Doc/Release/User-Contributions.html#Manipulating-Hook-Functions). Please file a bug over there.
