### ISSUE TITLE
Prompt clears content. (ascii display)

### ISSUE THREAD

**Issue by niksingh710** [marlonrichert/zsh-snap#203]
## Describe the bug

I want to display neofetch then the shell prompt. i use starship as prompt.  
i placed the neofetch command at the end of the .zshrc

## Steps To Reproduce

The code that initializes the prompt.
```zsh
    znap eval starship 'starship init zsh --print-full-init'
    prompt_starship_precmd
    znap prompt starship
```

## Expected behavior

neofetch output
then prompt

## Observed behavior

<details><summary>Click to expand</summary>
neofetch comes and then instantly gets cleared out and only the prompt remains.
commenting `znap prompt starship` makes it work but then the prompt is slow.

</details>

## Environment:
 - OS:  arch linux
 - Terminal:  foot
 - Zsh version:  5.9
 - Repo version:

**Comment by marlonrichert** [comment]
I don't see `neofetch` anywhere in the code you provided. I'll reopen this if you can provide me with a complete, runnable test case.
