### ISSUE TITLE
Installing command-not-found

### ISSUE THREAD

**Issue by joshcho** [marlonrichert/zsh-snap#204]
## Describe the bug

I am having trouble installing command-not-found in ohmyzsh.

## Steps To Reproduce

In my .zshrc,
```
znap source ohmyzsh/ohmyzsh
znap source ohmyzsh/ohmyzsh \
    plugins/command-not-found
```

doesn't quite work.
## Expected behavior

It should install properly.

## Observed behavior

The plugin doesn't work. In fact, ohmyzsh works with colored-man-pages, but not with command-not-found, which is a bit odd.

<details><summary>Click to expand</summary>

</details>

## Environment:
 - OS:  Arch Linux
 - Terminal:  Alacritty
 - Zsh version:  5.9
 - Repo version:  97e9904

**Comment by marlonrichert** [comment]
> doesn't quite work.

Please elaborate.
