### ISSUE TITLE
ASDF example missing steps

### ISSUE THREAD

**Issue by ghostsquad** [marlonrichert/zsh-snap#206]
## Describe the bug
The example for `znap install` includes `asdf`, however, this particular one is missing steps. E.g. when `asdf` is installed via homebrew, you need to add this to your ZSHRC:

```shell
source "$(brew --prefix asdf)/libexec/asdf.sh"
```

for znap, there's an extra step needed, which is to add the following to your `.zshrc`
```
source ~[asdf]/asdf.sh
```

## Steps To Reproduce

Prequisites for each test
- `brew uninstall asdf` 
- `znap uninstall asdf-vm/asdf`
- Ensure `.zshrc` doesn't have `source "$(brew --prefix asdf)/libexec/asdf.sh"` in it.
- Ensure `command asdf` fails
- Open new terminal window
- Observe via `echo $PATH` that `$HOME/.asdf/shims` is not listed

### Test 1
1. Run `brew install asdf`
2. Observe that, via `echo $PATH` that `$HOME/.asdf/shims` is _still_ not in path even after restarting terminal.
3. Run `source "$(brew --prefix asdf)/libexec/asdf.sh"` and observe the PATH now including `$HOME/.asdf/shims`

### Test 2
1. Run `znap install asdf-vm/asdf`
2. Observe that, via `echo $PATH` that `$HOME/.asdf/shims` is _still_ not in path even after restarting terminal.
3. Run `source ~[asdf]/asdf.sh` and observe the PATH now including `$HOME/.asdf/shims`

```zsh

```

## Expected behavior
I could use znap instead of homebrew to manage my ASDF installation, OR just the completions.

## Observed behavior
It wasn't quite as automatic as described.

## Environment:
 - OS: macOS 13.1
 - Terminal: iTerm2
 - Zsh version: `5.8.1`
 - Repo version: `main 97e9904 Don't let pull delete symlinks not managed by Znap`

## Additional context
related to #205

**Comment by marlonrichert** [comment]
Thanks for letting me know. However, I'm not really interested in trying to keep up to date with the installation instructions for specific software. Hence, I have for now simply removed most of the examples that refer to ASDF.
