### ISSUE TITLE
Some way to `znap fpath` don't generate the completion file every initizalition

### ISSUE THREAD

**Issue by henrique3g** [marlonrichert/zsh-snap#207]
## What do you want?
I want that the command `znap fpath` in my .zshrc file don't generate again the completion file every time that I open a new terminal.

## Why do you want this?

The way it works now delays the startup, It run the generator command every time that shell initialize.

## Who else would benefit from this?

All that use this command.

## How should it work?
Can have some check to verify if need to generate the file again, or some new command that force to generate again.

Given this situation:

* This will reduce the startup time of the shell.

When I perform these steps:

1. The user don't need to do any extra action.

Then I expect this to happen:

* When generate the file with the provided command and I open a new shell it can't run the command and generate the file again.
* Can have some default update time like every 24 hours to generate the file again or some new command that force to generate the file again if it already exist.

**Comment by henrique3g** [comment]
I had done a simple solution to this.
In the `.znap.fpath` file.

and I had commented the `.znap.compile $_P__file` line because I couldn't understand what this do and it consumes a lot of time on startup, if someone know if this can cause some problem tell me.

```zsh
#!/bin/zsh
# install command output as a function
# args: <function> <command>
emulate -L zsh; setopt $_znap_opts
zmodload -F zsh/files b:zf_mkdir

private _P__name=$1 _P__generator=$2 dir=${XDG_DATA_HOME:-~/.local/share}/zsh/site-functions
shift 2

zf_mkdir -pm 0700 $dir

private _P__file=$dir/$_P__name

private _P__day_seconds=86400
if [[ ! (-f $_P__file && "$(( $(date +"%s") - $(stat -c "%Y" "$_P__file") ))" -gt "$_P__day_seconds") ]]; then
  eval "$_P__generator" >| $_P__file ||
      return

  print -r -- "#$_P__generator" >>| $_P__file
  # .znap.compile $_P__file

fi

[[ -f $_comp_dumpfile ]] &&
    zf_rm -f $_comp_dumpfile

true
```

**Comment by marlonrichert** [comment]
> I want that the command `znap fpath` in my .zshrc file don't generate again the completion file every time that I open a new terminal.

It shouldn’t. Can you please provide a reproducible example for me?

**Comment by henrique3g** [comment]
As well? I did not understand sorry

**Comment by marlonrichert** [comment]
@henrique3g Provide me with the smallest `.zshrc` file possible that reproduces the problem.
