### ISSUE TITLE
znap pull errors

### ISSUE THREAD

**Issue by Stanzilla** [marlonrichert/zsh-snap#219]
## Describe the bug

Hitting a few errors when running znap pull
## Steps To Reproduce

`znap pull`

## Expected behavior

Update of all znap plugins

## Observed behavior

<details><summary>Click to expand</summary>
~[zsh-snap] main
❯ znap pull
.znap.status.task:8: command not found: ..znap.fetch
.znap.status.task:8: command not found: ..znap.fetch
.znap.status.task:8: command not found: ..znap.fetch
.znap.status.task:8: command not found: ..znap.fetch
.znap.status.task:8: command not found: ..znap.fetch
.znap.status.task:8: command not found: ..znap.fetch
.znap.status.task:8: command not found: ..znap.fetch
.znap.status.task:8: command not found: ..znap.fetch
.znap.status.task:8: command not found: ..znap.fetch
.znap.status.task:8: command not found: ..znap.fetch
.znap.status.task:8: command not found: ..znap.fetch
.znap.status.task:8: command not found: ..znap.fetch
.znap.status.task:8: command not found: ..znap.fetch
fast-syntax-highlighting .znap.status.task:8: command not found: ..znap.fetch
✓
From https://github.com/zdharma-continuum/fast-syntax-highlighting
 * branch            master     -> FETCH_HEAD
BUG: run-command.c:1521: you must provide a non-zero number of processes!
fzf-zsh-plugin [behind 2]

</details>

## Environment:
 - OS:   5.15.83.1-microsoft-standard-WSL2 #1 SMP x86_64 GNU/Linux
 - Terminal:  Windows Terminal
 - Zsh version:  zsh 5.9 (x86_64-ubuntu-linux-gnu)
 - Repo version:  main 9b8edd8 Handle missing upstream

**Comment by ptaranat** [comment]
This was fixed recently in #202. Try reinstalling zsh-snap.

**Comment by Stanzilla** [comment]
> This was fixed recently in #202. Try reinstalling zsh-snap.

I had pulled the latest commit before submitting the issue so I should be on the fixed version already

**Comment by ptaranat** [comment]
Hmm, might be different in your case. I ran into the same error, then pulled main branch. That didn't work, so I ran through the install step again, and it fixed it:
```
git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git
source zsh-snap/install.zsh
```

**Comment by Stanzilla** [comment]
I just ran the normal pull again and now it seems to have fixed itself, I guess the it was indeed missing another `source` after the update.

![image](https://user-images.githubusercontent.com/75278/218797568-affd395c-b44c-46bf-8d88-5d8b3cb238c3.png)
