### ISSUE TITLE
Feature request - add tests

### ISSUE THREAD

**Issue by mattmc3** [marlonrichert/zsh-snap#22]
Would you be open to adding tests to znap? Or, alternatively, would you be open to me submitting a PR that adds some? A couple of times recently critical functionality has broken in znap that I think having tests would have easily caught (https://github.com/marlonrichert/zsh-snap/issues/17 https://github.com/marlonrichert/zsh-snap/issues/14#issuecomment-758112520).

I'd be happy to submit a PR that has [ZTAP](https://github.com/mattmc3/ztap) unit tests if you're interested. Here's an example of how they might look: https://github.com/mattmc3/pz/tree/main/tests

**Comment by marlonrichert** [comment]
I'm definitely open to adding tests and accepting PRs. However, I would prefer to go with something more established. Here's two shell testing frameworks that look promising to me:
* [ShellSpec](https://github.com/shellspec/shellspec)
* [shUnit2](https://github.com/kward/shunit2)

**Comment by mattmc3** [comment]
Hey @marlonrichert! Seems like you have an idea in mind how you'd like your tests built, and as I have no experience with either of those tools, I'll leave it to you. Those frameworks seem more heavy weight than what I prefer when doing my own tests. Thanks for the great work on zsh-snap.

**Comment by marlonrichert** [comment]
@mattmc3 I've started adding light-weight unit tests, using [`clitest`](https://github.com/aureliojargas/clitest#readme): https://github.com/marlonrichert/zsh-snap/tree/main/.clitest

Thank you for motivating me to get started! 👍🏽
