### ISSUE TITLE
`znap eval` no longer works for non-repos

### ISSUE THREAD

**Issue by EvanDurfee** [marlonrichert/zsh-snap#239]
## Describe the bug

The command `znap eval ( <repo> | <name> ) <command>`  treats regular names as though they were a repo, causing directory expansion to fail.

## Steps To Reproduce

```zsh
# source znap in zshrc
source "$XDG_DATA_HOME"/zsh-snap/zsh-snap/znap.zsh
# eval something
znap eval test echo echo hello
```

## Expected behavior

I expect the output to cached under ~/.cache/zsh-snap and be reused on future invocations.

```zsh
znap eval test echo echo hello
```

```text
hello
```

## Observed behavior

```zsh
znap eval test echo echo hello
```

```text
.znap.eval:42: no directory expansion: ~[test]
```

If I checkout an older znap version (b1e0cf61f395ce370bbb626ff27aa31ac8ef1b69, from April 28), the `eval` command works as expected. I didn't check all of the intervening commits, but I know that one works.

## Environment:
 - OS: Fedora 38
 - Terminal: Gnome Terminal
 - Zsh version: zsh 5.9 (x86_64-redhat-linux-gnu)
 - Repo version: * main d1f282b Add setting for `compinit` arguments

**Comment by jake-klingler** [comment]
Running into the same issue on latest version.

Common eval directives like: 
`znap eval zoxide 'zoxide init zsh --cmd j'`
and 
`znap eval direnv 'direnv hook zsh'`
are completely breaking my shell. 

OS: macOS 13.3.1
Terminal: iTerm2
Zsh: 5.9 (x86_64-apple-darwin21.3.0)

**Comment by UBtrNvME** [comment]
Same for me.

`
znap eval starship 'starship init zsh --print-full-init'
znap prompt starship
`
Outputs:
`.znap.eval:42: no directory expansion: ~[starship]`

OS: Ubuntu 22.04
Terminal: Windows Terminal
Zsh: zsh 5.8.1 (x86_64-ubuntu-linux-gnu)
Repo version: 62abac7 (HEAD -> main, origin/main, origin/HEAD) Fix typo in README.md

**Comment by 343dev** [comment]
Hi there.

I'am on 4ec387d and still have the same problem.

```
.znap.prompt:9: no directory expansion: ~[starship]
```

starship prompt is installed via Homebrew.
