### ISSUE TITLE
znap clone <url> broken

### ISSUE THREAD

**Issue by sedlund** [marlonrichert/zsh-snap#240]
## Describe the bug
znap clone <url> is broken

## Steps To Reproduce

```zsh

 znap clone https://github.com/romkatv/powerlevel10k
znap clone: invalid argument 'https://github.com/romkatv/powerlevel10k'
Usage: znap clone ( <user>/<repo> | <url> ) ...
Download repos in parallel.


```

## Expected behavior
cloning to work by url as before

## Observed behavior

<details><summary>Click to expand</summary>

</details>

## Environment:
 - OS: 
 - Terminal: 
 - Zsh version: 
 - Repo version:

**Comment by marlonrichert** [comment]
That's not a valid Git remote URL. Use `https://github.com/romkatv/powerlevel10k.git` instead.
