### ISSUE TITLE
`znap eval` with repo no longer works

### ISSUE THREAD

**Issue by patrickli** [marlonrichert/zsh-snap#244]
## Describe the bug

Since the recent update `znap eval` with both repo and command no longer works, at least for `LS_COLORS`.

## Steps To Reproduce

The following is copied directly form https://github.com/marlonrichert/zsh-snap/blob/main/.zshrc#L71
```zsh
znap eval trapd00r/LS_COLORS "$( whence -a dircolors gdircolors ) -b LS_COLORS"
```

## Expected behavior

A new terminal should launch with no errros.

## Observed behavior

<details><summary>Click to expand</summary>

The following error is printed when launching a new terminal.
```
znap eval: generating cache for $'dircolors\n/usr/local/bin/gdircolors -b LS_COLORS'
.znap.eval:43: no such file or directory: /Users/Patrick.Li/.cache/zsh-snap/eval//trapd00r/LS_COLORS.zsh
.znap.eval:44: no such file or directory: /Users/Patrick.Li/.cache/zsh-snap/eval//trapd00r/LS_COLORS.zsh
.znap.eval:LS_COLORS.zsh:.:1: no such file or directory: /Users/Patrick.Li/.cache/zsh-snap/eval//trapd00r/LS_COLORS.zsh
```
</details>

## Environment:
 - OS: MacOS Ventura 13.3.1
 - Terminal: iTerm2
 - Zsh version: `5.9`
 - Repo version: 4ec387d

**Comment by nimish** [comment]
Can also confirm. Similar setup.
