### ISSUE TITLE
auto completion not working

### ISSUE THREAD

**Issue by shdennlin** [marlonrichert/zsh-snap#254]
## Describe the bug

when the first start the terminal after re-configure `.zshrc` file, the completion of znap will work, but after 2nd start terminal, completion will not work.

## Steps To Reproduce

```zsh
# file: .zshrc
[[ -r ~/.znap/zsh-snap/znap.zsh ]] || {
    git clone --depth 1 -- \
        https://github.com/marlonrichert/zsh-snap.git ~/.znap/zsh-snap
}
source ~/.znap/zsh-snap/znap.zsh
```

## Expected behavior

`znap` completions are available

## Observed behavior

<details><summary>video demo</summary>

https://github.com/marlonrichert/zsh-snap/assets/68002539/1cb7313c-ecb0-4ff5-bdb2-ccd5d0842b92

</details>

`znap` completions are not available:

```zsh
$ which _znap
_znap not found
```

## Environment:
 - OS: Ubuntu 23.04
 - Terminal: Gnome Terminal
 - Zsh version: zsh 5.9 (x86_64-ubuntu-linux-gnu)
 - Repo version: 60d478e

## Additional context

After I add the following at the end of `.bashrc`
```zsh
znap fpath _ ':'
```
The completion can work normally. Why?

**Comment by marlonrichert** [comment]
Which terminal do you use? Can you share screenshots of the settings?

**Comment by shdennlin** [comment]
I have already put the demo video in https://github.com/marlonrichert/zsh-snap/issues/254#issue-1749605319 - Observed behavior
Configuration can be found at 0:31 seconds

Terminal: `Gnome Terminal`

**Comment by marlonrichert** [comment]
@shdennlin Please share your *terminal’s* settings, not your shell’s.
