### ISSUE TITLE
znap latest is broken when installed to /etc/znap

### ISSUE THREAD

**Issue by terala-work** [marlonrichert/zsh-snap#259]
## Describe the bug
I've had `znap` cloned to `/etc/znap` in my linux installations. It worked fine without issues until the update to the latest which complete broke it.

## Steps To Reproduce

1. git clone  to /etc/znap
2. In user's .zshrc : `source /etc/znap/znap.zsh` 

## Expected behavior
`znap` to fully initialize, function normally.

## Observed behavior
`znap` fails to find `init.zsh` and is left in a non-functional state.

## Environment:
 - OS: Ubuntu 23.04
 - Terminal: Gnome Terminal
 - Zsh version: 5.9
 - Repo version: `7441929`

## Additional context
None

**Comment by marlonrichert** [comment]
You could try to debug this by putting `set -x` before the `source` statement. Patches welcome, but I'm not going to investigate this myself.

**Comment by marlonrichert** [comment]
1. Put `set -x` one line before you source Znap.
1. Find where the first wrong value is set.
1. Look up the code where this happens.
1. Fix the problem, if possible. If not, add a workaround to the Readme.
