### ISSUE TITLE
prompt prints twice

### ISSUE THREAD

**Issue by Stanzilla** [marlonrichert/zsh-snap#26]
Using `znap prompt sindresorhus/pure` my prompt always prints twice when opening a new session, once without git info and once with. maybe because of the use of `async`?

![image](https://user-images.githubusercontent.com/75278/106401131-bc8db000-6422-11eb-853a-68d251974e74.png)

**Comment by marlonrichert** [comment]
> maybe because of the use of `async`?

No, it was just a silly bug on my part, which coincidentally only manifested with `pure`. It's fixed now.

**Comment by Stanzilla** [comment]
Awesome, thank you!
