### ISSUE TITLE
[Feature] Ability to clean cached `eval`

### ISSUE THREAD

**Issue by joe733** [marlonrichert/zsh-snap#260]
## What do you want?

`znap eval` caches the results. For non-repo `eval`s, one needs to change the `<command>` name to invalidate the cache.

## Why do you want this?

I want to be able to use the same `<command>` name.

## Who else would benefit from this?

Every `Zsh-Snap` user.

## How should it work?

For example when installing auto-completions for `pipx` I had to make a few attempts to get it right.

```zsh
append_path $HOME/.local/bin
znap eval pipx-completions 'register-python-argcomplete pipx'
```

But every time I had to change the `<command>` in `znap eval` to test it, otherwise the old cached `<command>` would be sourced.

When I run `znap clean` I would like to have option to remove all or individual cached `<command>`s from `${XDG_CACHE_HOME:-$HOME/.cache}/zsh-snap/eval`

---

Thanks a ton for Zsh-Snap! It's the prime reason for having a very fast startup time with lots of features.

**Comment by marlonrichert** [comment]
> For non-repo `eval`s, one needs to change the `<command>` name to invalidate the cache.

Or you can just delete the cache manually: `rm ${XDG_CACHE_HOME:-$HOME/.cache}/zsh-snap/eval/<command>.zsh`

**Comment by marlonrichert** [comment]
Won't fix. See #261.
