### ISSUE TITLE
Cache command output for `znap fpath`

### ISSUE THREAD

**Issue by vhdirk** [marlonrichert/zsh-snap#266]
## Describe the bug
`znap fpath` does not cache the result of the function it evaluates, causing it to run everytime a new terminal is openened.  
While the prompt renders immediately, the first command then takes some time.

## Steps To Reproduce

In `.zshrc`:
```zsh

REPOS_DIR=$HOME/.dotfiles/repos
[[ -r $REPOS_DIR/zsh-snap/znap.zsh ]] || git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git $REPOS_DIR/zsh-snap
source $REPOS_DIR/zsh-snap/znap.zsh  # Start Znap

_has() {
  command -v "$1" 1>/dev/null 2>&1
}

if _has helm; then
  znap fpath _helm 'echo `date` >> /tmp/shouldnottouch && helm completion zsh'
fi

```
Then open a new terminal. Then open another one.

## Expected behavior
If the output of `helm completion zsh` is cached, `/tmp/shouldnottouch` should only contain a single line

## Observed behavior
`/tmp/shouldnottouch` contains 2 lines, meaning that the command ran twice

## Environment:
 - OS: Debian 6.4.13-1 x86_64 GNU/Linux
 - Terminal: Gnome Terminal
 - Zsh version: zsh 5.9 (x86_64-debian-linux-gnu)
 - Repo version: 7741929695f0e4761971e951ab81cb7c2bd9910f

**Comment by vhdirk** [comment]
After reading the docs once again, I must admit I was mistaken. It doesn't mention caching for fpath anywhere. So this is actually more of a feature request

**Comment by marlonrichert** [comment]
I'm going to replace built-in caching of `znap` commands with a dedicated `znap cache` command. So, I will close this issue, but you'll be able to use that instead. 🙂
