### ISSUE TITLE
How can one setup Rust lang completions using znap

### ISSUE THREAD

**Issue by thepreacher** [marlonrichert/zsh-snap#27]
So I'm slowly trying to move as much of zsh control over to znap and when I try to generate completions for rust with the code below I get the error `_arguments:comparguments:325: can only be called from completion function`

```
# rust and cargo completions
znap eval rust-completion 'rustup completions zsh'
znap eval cargo-completion 'rustup completions zsh cargo'
```
I wondering how you'll go about it.

**Comment by marlonrichert** [comment]
`znap eval 'foo'` is a direct replacement for `eval "$(foo)"` only. What you are trying to replace is
```zsh
rustup completions zsh > ~/.zfunc/_rustup
fpath+=~/.zfunc
```
You need one extra step to get what you want:
```zsh
znap function _rustup 'znap eval rustup-completion "rustup completions zsh"'
compdef _rustup rustup
```
