### ISSUE TITLE
Prompt fails to load and terminal session immedately exits

### ISSUE THREAD

**Issue by erdemoney** [marlonrichert/zsh-snap#272]
Intermittently I will get in this state where the prompt fails to load and I no longer can open terminals windows. They immediately exit with the below error. The only way to recover is to either reboot or remove the prompt line from my zshrc using TextEdit.

```
Last login: Thu Oct 12 16:14:38 on ttys001
.znap.prompt:20: process substitution failed: permission denied
zsh(37713,0x1f2f96080) malloc: *** error for object 0x105170cd8: pointer being freed was not allocated
zsh(37713,0x1f2f96080) malloc: *** set a breakpoint in malloc_error_break to debug

[Process completed]
```
my zshrc
```
#!/bin/zsh

# change directories without cd
setopt autocd

# source aliases
source ~/.aliases

# source env vars
source ~/.zshenv

# Download Znap, if it's not there yet.
[[ -f ~/.zsh_plugins/zsh-snap/znap.zsh ]] ||
    git clone --depth 1 -- \
        https://github.com/marlonrichert/zsh-snap.git ~/.zsh_plugins/zsh-snap

source ~/.zsh_plugins/zsh-snap/znap.zsh  # Start Znap

# `znap prompt` makes your prompt visible in just 15-40ms!
znap prompt sindresorhus/pure

# `znap source` automatically downloads and starts your plugins.
# znap source marlonrichert/zsh-autocomplete
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting
znap source chriskempson/base16-shell

# `znap eval` caches and runs any kind of command output for you.
eval "$(zoxide init zsh)"
```

## Environment:
 - OS: macOS
 - Terminal: Terminal.app, Kitty, iTerm
 - Zsh version: 5.89
 - Repo version: main 7741929 Fix handling of `git@*:*.git` URLs

**Comment by marlonrichert** [comment]
It fails on this line: https://github.com/marlonrichert/zsh-snap/blob/755566ca73bfe3cc229fe90fcc0ba87d58325771/functions/.znap.prompt#L28

That means it's either a bug in Zsh or something failing on your file system. Please report to the [official Zsh mailing list](https://zsh.sourceforge.io/Arc/mlist.html).
