### ISSUE TITLE
Typo in README ("znal eval")

### ISSUE THREAD

**Issue by michaeldebetaz** [marlonrichert/zsh-snap#276]
Hi @marlonrichert 👋 Thanks for your amazing work with zsh snap!

I just want to report a typo in your doc: https://github.com/marlonrichert/zsh-snap?tab=readme-ov-file#faster-eval

> ### Faster eval
> `znal eval <name> '<command>'`
> This can be up 10 times faster than a regular eval "$( <command> )" statement! If you pass a > repo as the

Should be znap eval, right?

**Comment by marlonrichert** [comment]
Thanks for reporting!
