### ISSUE TITLE
Shell randomly shuts down terminal

### ISSUE THREAD

**Issue by martynwheeler** [marlonrichert/zsh-snap#28]
Hi,

I am fairly new to zsh and customisations.  I installed znap and have the following for my .zshrc file:

```
# start znap
source ~/git/zsh-snap/znap.zsh

# `znap prompt` makes your prompt appear in ~40ms. You can start typing right away!
znap prompt denysdovhan/spaceship-prompt

# Use `znap source` to load only those parts of Oh-My-Zsh or Prezto that you really need:
znap source sorin-ionescu/prezto
znap source sorin-ionescu/prezto \
  modules/{environment,completion,terminal,editor,history,directory,syntax-highlighting,history-substring-search,utilit
y}

znap source ohmyzsh/ohmyzsh \
  lib/{git,theme-and-appearance} \
  plugins/git

# Use `znap source` to load your plugins:
znap source zsh-users/zsh-completions
znap source zsh-users/zsh-syntax-highlighting
znap source momo-lab/zsh-abbrev-alias
znap source ael-code/zsh-colored-man-pages

SPACESHIP_PROMPT_SEPARATE_LINE=false
SPACESHIP_USER_SHOW=always
```

For some reason I am getting random crashes of my shell where it just shuts down in the middle of a session (sometimes at the start too) - I cannot see a pattern that is causing it to shutdown.  What is the easiest way to debug the shell?  Is there a way of seeing a log to see what is causing the shutdown?

Thank you,

Martyn

**Comment by marlonrichert** [comment]
The easiest way to debug is to restart your shell with `exec zsh -xv`.

**Comment by marlonrichert** [comment]
Did you notice there's an unwanted line break in this statement?
```zsh
znap source sorin-ionescu/prezto \
  modules/{environment,completion,terminal,editor,history,directory,syntax-highlighting,history-substring-search,utilit
y}
```
Or is that just a copy-paste error?

**Comment by marlonrichert** [comment]
If I fix that line break, your `.zshrc` file works just fine for me. I'm not seeing any crashes. Do you have any other config files and if so, what's in them? The full list of possible config files that Zsh reads on startup can be found here: http://zsh.sourceforge.net/Doc/Release/Files.html#Files-2

**Comment by martynwheeler** [comment]
> Did you notice there's an unwanted line break in this statement?
> 
> ```shell
> znap source sorin-ionescu/prezto \
>   modules/{environment,completion,terminal,editor,history,directory,syntax-highlighting,history-substring-search,utilit
> y}
> ```
> 
> Or is that just a copy-paste error?

I will check if that is an error when I get home.  I will also look at your other suggestions and try and work out what causes it to shutdown.

Thank you!

**Comment by martynwheeler** [comment]
It seems to happen when I am holding down a key for some reason (eg holding down space while looking at the output of a more command).  It suddenly just closes?  I can't reproduce it reliably though.

Martyn

**Comment by marlonrichert** [comment]
> It seems to happen when I am holding down a key for some reason (eg holding down space while looking at the output of a more command).

That definitely has nothing to do with Znap. You could try asking for help on the Zsh mailing list: http://zsh.sourceforge.net/Arc/mlist.html

**Comment by notsocafe** [comment]
I can confirm this issue while using znap but I cannot reproduce it reliably either.

From a crash I've experimented a few mins ago as root : `zsh: error on tty read: Input/output error`

Unfortunately, I am unable to provide you with any additional information. This happens while running znap without any plugins or configuration.

**Comment by marlonrichert** [comment]
@martynwheeler @notsocafe Can you reproduce the bug with this template?
```zsh
$ znap pull
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD exec zsh -f  # Restart Zsh without config files in this dir.
% source /path/to/zsh-snap/znap.zsh
% # Test and document the steps to reproduce the problem.
```

**Comment by martynwheeler** [comment]
I have moved to a different distro and am no longer facing an issue

**Comment by marlonrichert** [comment]
I'm also doubtful this is an issue with Znap. Apart from compiling scripts and functions in the background (which finished very quickly), Znap doesn't actively do anything after the shell has started up.
