### ISSUE TITLE
Partial lines

### ISSUE THREAD

**Issue by ewjoachim** [marlonrichert/zsh-snap#29]
I'm 100% *not* sure that znap is involved in this bug but it's the most likely explaination.

When a command issues a partial line (a line without a final `\n`), zsh used to display a bold `%`. Now, and I believe since I've started using znap, my 2-line prompt overwrites the partial line.

Do you have an idea if this may be because of znap or if I should look elsewhere ?

**Comment by marlonrichert** [comment]
Yes, that was `znap prompt` that did that. It was necessary to avoid getting a bold `%` on the first prompt for some themes, but I now found another way around that and fixed your issue.

**Comment by ewjoachim** [comment]
Thanks for your reactivity ! Always a pleasure using your software :)

**Comment by ewjoachim** [comment]
Tested with `echo -n "yay"`, works perfectly thanks !
