### ISSUE TITLE
Is there a command to delete the plugins?

### ISSUE THREAD

**Issue by FardeenCodes** [marlonrichert/zsh-snap#30]
I loaded plugin and now i want to delete it i know i can 
use `rm -r ~.znap/<plugin>` but is there a  command for doing this.

**Comment by marlonrichert** [comment]
Yes, there is:
```zsh
znap rm <plugin>
```

Type `znap` without arguments for a full list of all Znap commands. Type `znap help <command>` for more info on a command.
