### ISSUE TITLE
Document/Confirm Minimum Supported ZSH Version

### ISSUE THREAD

**Issue by sacsar** [marlonrichert/zsh-snap#39]
I've been trying to use znap on RHEL7 and have discovered that it doesn't work with ZSH 5.0.2. I managed to change a few things, but haven't gotten it to work.

Things that I found:
- The `typeset` keyword doesn't exist, so `typeset -gHa _znap_opts=(...)` (and similarly for the other arrays) has to be split over two lines:
```
typeset -gHa _znap_opts
_znap_opts=(...)
```
- the `globstarshort` option doesn't exist (so I just removed it)
- `$funcdir/*znap*~*.zwc` doesn't match anything (as a result of removing `globstarshort` I assume), but I don't understand what the `.zwc` does/means, so I haven't been able to figure out how to get past this (if you remove `NO_nomatch`, you get further, but `:zinit:` isn't defined).

Naturally, support for zsh 5.0 would be awesome, but it would be good to note a minimum supported version in the README. (I can confirm 5.7.1 and 5.8 (on Catalina and Big Sur, respectively) are fine.)

**Comment by sacsar** [comment]
Okay, now I understand what `*~*.zwc` means. I *think* the issue is that `basedir` and thus `funcdir` aren't being set properly.

**Comment by marlonrichert** [comment]
Sorry, no, I have not tested Znap with Zsh 5.0.2. I test only with 5.7 and 5.8. My best guess is that the minimum required Zsh version is 5.3. I will investigate what is the actual minimum required and put it in the Readme.

**Comment by marlonrichert** [comment]
> Okay, now I understand what `*~*.zwc` means. I *think* the issue is that `basedir` and thus `funcdir` aren't being set properly.

I'm testing with Zsh 5.0.5 and `$funcdir/*znap*~*.zwc` works for me, but then the problem is that `autoload` doesn't accept absolute paths in Zsh 5.0.

I can make Znap compatible with Zsh 5.0.5, but it's going to take quite a bit of work. Right now, this is quite low priority for me.

**Comment by marlonrichert** [comment]
I added a note to the Readme. I won't be able to make Znap work with Zsh 5.0.x, though. In theory, Znap _could_ work with Zsh 5.3 or newer, but I'm able to test only with Zsh 5.7 and 5.8.
