### ISSUE TITLE
znap pull sends my fans spinning

### ISSUE THREAD

**Issue by thepreacher** [marlonrichert/zsh-snap#4]
Whenever I issue the command `znap pull`, the fans on my 2019, 12 core macbook pro starts spinning hard. I tried it multiple times and each time I have to kill all zsh processes to make it stop.

**Comment by marlonrichert** [comment]
I have a 2017, 2-core MacBook Pro and I hear not even a whisper from my fans. Activity Monitor doesn't show anything worth mentioning either. There must be something else going on on your machine. Please try to put together a reproducible test case for this, then I can look into it.
