### ISSUE TITLE
Auto-remove unused plugins

### ISSUE THREAD

**Issue by seivan** [marlonrichert/zsh-snap#41]
This would help like cleaning and reference checking when starting a new prompt. 
Right now old plugins are left behind, even when removed from `.zshrc`.
It doesn't have to be intelligent, could just be purging the plugins folder and fetching everything again.

**Comment by seivan** [comment]
Yeah but my suggestion was it could be self-managed. 
or something alongside `znap plugins reload` that would purge and reinstall, that way it would remove plugins no longer listed in e.g  `.plugins.zsh" instead of manually having to delete them.

**Comment by marlonrichert** [comment]
Ah, now I understand it. Yes, that’s a nice idea. 👍🏽

**Comment by marlonrichert** [comment]
I gave this some more thought and decided against it. I manage many non-plugin repos with `znap` and I wouldn't want those to get auto-removed. Besides, it is fairly straightforward to remove a plugin yourself:
* Type `ls ~znap` to see which repos are managed by Znap.
* Type `znap uninstall <repo>` to remove one.
