### ISSUE TITLE
znap eval doesn't seem to run.

### ISSUE THREAD

**Issue by lkhphuc** [marlonrichert/zsh-snap#44]
I tried to install LS_COLOR according to the README but not possible. There is no LS_COLOR variable output in the shell after startup.
Same thing for other `znap eval ..` command.

**Comment by lkhphuc** [comment]
I think `znap eval ...` doesn't execute in the correct folder. Simple example:
```
znap znap clone trapd00r/LS_COLORS
znap eval LS_COLORS 'echo $(pwd)'
```

The content in `.../LS_COLORS.zsh` is `/User/phuc`.

There is also a very brief flash of "... permission denied" every time zsh is started with the above config as well.

**Comment by marlonrichert** [comment]
Can you please try the following?
```zsh
> cd $(mktemp -d)
> HOME=$PWD ZDOTDIR=$PWD zsh -f
% source /path/to/znap.zsh
% znap clone trapd00r/LS_COLORS
% znap eval LS_COLORS 'echo $(pwd)'
```
Does it work then? If so, then there’s something else in your `.zshrc` file that’s interfering.

Also, what version of Zsh do you use?

**Comment by marlonrichert** [comment]
Some more questions:
* What happens when you do `cd ~znap`?
* What happens when you do `cd ~[LS_COLORS]`
* What options do you set in your `.zshrc` file?

**Comment by lkhphuc** [comment]
> ```shell
> % znap eval LS_COLORS 'echo $(pwd)'
> ```
even in this example there is permission erro : `/Users/phuc/.zsh-snap/LS_COLORS.zsh:2: permission denied: /var/folders/cj/c9z2_lvj47949k2s0x7tpqp40000gn/T/tmp.hpihHyps`

`~znap`, `~[LS_COLOR]` all work fine, I can cd into them.

My current workaround is to use the shortcut explicitly: `znap eval LS_COLORS 'dircolors -b ~[LS_COLORS]/LS_COLORS'`

**Comment by marlonrichert** [comment]
I just looked into it and it appears I must've accidentally deleted some code. Sorry about that. I will push in a fix soon.

**Comment by marlonrichert** [comment]
Fixed.

**Comment by lkhphuc** [comment]
Thanks. Just switch from `zinit` and love the plugin so far. Prompt is instant and the zshrc actually makes sense to me now.

**Comment by marlonrichert** [comment]
@lkhphuc Oh, and I forgot to mention: As an added bonus, if you now use `znap eval trapd00r/LS_COLORS 'gdircolors -b LS_COLORS'`, then you no longer need the separate `znap clone` statement.
