### ISSUE TITLE
znap attempts to delete files from zsh-common on first use

### ISSUE THREAD

**Issue by notsocafe** [marlonrichert/zsh-snap#5]
I am currently running zsh 5.7.1 on Debian Buster, and I have just installed znap using the recommended method in the README.  

On the very first usage of znap (`znap clone` to be precise), it attempted to remove several completion files provided by the `zsh-common` package : 

```
rm: cannot remove '/usr/share/zsh/functions/Completion/AIX.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/Completion/Base.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/Completion/BSD.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/Completion/Cygwin.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/Completion/Darwin.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/Completion/Debian.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/Completion/Linux.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/Completion/Mandriva.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/Completion/openSUSE.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/Completion/Redhat.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/Completion/Solaris.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/Completion/Unix.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/Completion/X.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/Completion/Zsh.zwc': Permission denied
rm: cannot remove '/usr/share/zsh/functions/VCS_Info/Backends.zwc': Permission denied
```

I've successfully reproduced the issue on another Debian Buster install.

Steps to reproduce : 
* Install znap using the recommended way (`mkdir -p ~/.zsh && git clone https://github.com/marlonrichert/zsh-snap.git zsh-snap` with the related source command inside `.zshrc`)
* Run `znap clone` with any repository

Please let me know if you need any additional information.

**Comment by notsocafe** [comment]
I'm not a zsh expert, but I've managed to isolate the source of the issue, inside `znap clean`. 

On Debian, several compiled files and source directories are provided through `zsh-common`. On installation, files are keeping their original creation date, while folders don't, therefore tripping `znap clean`.  

Case in point : 
```
drwxr-xr-x  2 root root    4096 XXX XX  2020 openSUSE
-rw-r--r--  1 root root   24520 Feb  5  2019 openSUSE.zwc
```

One way to fix this would be to check whether the source file is actually a directory, and compare individual file creation dates.

**Comment by marlonrichert** [comment]
Should be fixed now.

**Comment by notsocafe** [comment]
Thanks for the quick fix ! I can confirm the issue is fixed :)
