### ISSUE TITLE
`(anon):3: unrecognized modifier` when using `%~` in a custom prompt and moving inside a plugin's directory

### ISSUE THREAD

**Issue by notsocafe** [marlonrichert/zsh-snap#58]
Fairly straightforward test case :
* `git clone https://github.com/marlonrichert/zsh-snap.git ~/.zsh/zsh-snap`
* `echo -e 'source ~/.zsh/zsh-snap/znap.zsh\nexport PS1="%~%# "' > ~/.zshrc`
* `mkdir ~/.zsh/test`

When restarting the shell, this happens :
```
~% cd .zsh
~znap% cd test
(anon):3: unrecognized modifier
```

Reproduced on Debian Buster with zsh 5.7.1 and znap at current latest commit (7e713a2).

**Comment by marlonrichert** [comment]
It appears I'm using a feature from Zsh 5.8 that's not available in Zsh 5.7:
> The history expansion !:1:t2 used to be interpreted such that the 2 was a separate character added after the history expansion. Now it is an argument to the :t modifier. The behaviour of :h has similarly changed.

http://zsh.sourceforge.net/releases.html

**Comment by marlonrichert** [comment]
Fixed.
