### ISSUE TITLE
znap rm <package> error

### ISSUE THREAD

**Issue by thepreacher** [marlonrichert/zsh-snap#6]
I tried to remove "fast-syntax-highlighting" using `znap rm fast-syntax-highlighting` got following error message:

```
trash -F fast-syntax-highlighting
Specify at least one path
```

From the command prompt and within the plugins directory, I typed `trash fast-syntax-highlighting` and it worked. I think the the `-F` flag has something to do with it. [znap.rm](https://github.com/marlonrichert/zsh-snap/blob/main/functions/.znap.rm)

**Comment by marlonrichert** [comment]
Ah, it seems that there's more than one command-line tool called `trash`. That's annoying. I'll probably have to forgo using that command, then.

**Comment by marlonrichert** [comment]
Fixed.
