### ISSUE TITLE
Possible interoperability issue with example .zshrc

### ISSUE THREAD

**Issue by YenLegion** [marlonrichert/zsh-snap#65]
I think there may be an interoperability issue with the given example .zshrc file. 

Line 49:

znap eval trapd00r/LS_COLORS 'gdircolors -b LS_COLORS'

Example eval is gdircolors, I think this may OSX specific. I realize it's just an example, but in the spirit of a plugin manager that is easy to comprehend I thought it might be worth making this issue.

**Comment by marlonrichert** [comment]
Fixed.
