### ISSUE TITLE
Using prompt repos that aren't "zsh themes"

### ISSUE THREAD

**Issue by eddyg** [marlonrichert/zsh-snap#66]
Is it possible to use `znap prompt` to load something like [agkozak-zsh-prompt](https://github.com/agkozak/agkozak-zsh-prompt)?

It has a `.plugin.zsh` script instead of a `.zsh-theme` one, but the install instructions say it can be installed for use with OMZ by creating a symlink to point a `zsh-theme` link at the `plugin.zsh` file, so I'm curious if there's a way for Znap! to handle this.

Thanks!

**Comment by marlonrichert** [comment]
It's possible now: 0aa6d36.

**Comment by eddyg** [comment]
Thanks Marlon! Really digging the ease-of-use of Znap! so far. 👍

**Comment by eddyg** [comment]
OK, I just had a chance to try this out. I **removed**:

```
znap source agkozak/agkozak-zsh-prompt
```

from from my `.zshrc` and **replaced** it with:

```
znap prompt agkozak/agkozak-zsh-prompt
```

but now my prompt shows up like this: 😜 

```
}me }~${AGKOZAK_PROMPT_WHITESPACE}}${AGKOZAK_PROMPT_CHAR[1]:-%}
```

For ref:

```
me ~
❯ cd ~[zsh-snap]
me ~[zsh-snap] (main)
❯ git show --pretty=oneline --summary
42c06c98 (HEAD -> main, origin/main, origin/HEAD) Improve `znap restart` validation logic
me ~[zsh-snap] (main)
❯
```

**Comment by marlonrichert** [comment]
Should be fixed now.

Note, though, that for the best experience, the theme you pass to `znap prompt` should implement [Zsh's `promptinit` API](http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Writing-Themes). You might want to file an issue about that with [agkozak/agkozak-zsh-prompt](https://github.com/agkozak/agkozak-zsh-prompt).
