### ISSUE TITLE
Following Symlinks on WSL in Windows FS

### ISSUE THREAD

**Issue by YenLegion** [marlonrichert/zsh-snap#71]
On WSL when I run 'znap clean' or 'znap compile' it takes a very long time to complete or eventually outputs errors. I think it is trying to compile/clean files on the Windows filesystem. Is it possible to set znap to not follow symlinks, or limit how far it recurses into directories? Here is an example of the compile error I got. 

.znap.compile.next:17: too many levels of symbolic links: Application Data     
.znap.compile.next:17: too many levels of symbolic links: History
.znap.compile.next:17: too many levels of symbolic links: Temporary Internet Files

Thanks.

**Comment by marlonrichert** [comment]
I don't have access to WSL, but I can definitely introduce a setting for Znap commands not to follow symlinks. Coming soon.™

**Comment by marlonrichert** [comment]
I decided to just disable symlink traversal. I will add a setting if anyone complains.

**Comment by YenLegion** [comment]
Thank you, works great on WSL.
