### ISSUE TITLE
Parse out command line options

### ISSUE THREAD

**Issue by marlonrichert** [marlonrichert/zsh-snap#8]
Currently, none of Znap's commands expect any options. This can lead to silly situations, such as when you type `znap prompt -h`, you are shown the help text of the `prompt` function, which is misleading.

This needs to be handled somehow.

**Comment by ewjoachim** [comment]
Ooooooh, That's why it does this ! Thanks :)

**Comment by marlonrichert** [comment]
Fixed. You can now pass `-h` or `--help` to any Znap command to get usage notes and help text.
