### ISSUE TITLE
extended history information is erased when using 'znap restart'

### ISSUE THREAD

**Issue by EvanDurfee** [marlonrichert/zsh-snap#82]
When running znap restart, I've noticed that the zsh history file has all of its timestamp data removed when the extended_history option is enabled. It's preserved if the shell is closed and started again normally, but not when using znap restart.
```
❯ cat /tmp/zshhistfile
: 1624525166:0;sleep 1
: 1624525166:0;exit
: 1624525166:0;cat /tmp/zshhistfile
: 1624525166:0;sleep 3
: 1624525166:0;ls
: 1624525166:0;znap restart
: 1624525128:0;cat /tmp/zshhistfile
: 1624525129:0;ls
: 1624525131:0;cat /tmp/zshhistfile
: 1624525148:0;pwd
: 1624525153:0;cat /tmp/zshhistfile
: 1624525166:0;exit
❯ znap restart
Validating dotfiles...
Restarting Zsh...
❯ cat /tmp/zshhistfile
sleep 1
exit
cat /tmp/zshhistfile
sleep 3
ls
znap restart
cat /tmp/zshhistfile
ls
cat /tmp/zshhistfile
pwd
cat /tmp/zshhistfile
exit
cat /tmp/zshhistfile
znap restart
```

**Comment by marlonrichert** [comment]
Do you know in which file on your machine `extended_history` gets set?

**Comment by EvanDurfee** [comment]
$ZDOTDIR/.zshrc

**Comment by marlonrichert** [comment]
> It's preserved if the shell is closed and started again normally

Exactly what do you mean with that? How do you normally close your shell and start it again?

**Comment by EvanDurfee** [comment]
What I meant by that was closing the shell completely, either via the exit command or by closing the terminal emulator, then starting up a new instance.

**Comment by marlonrichert** [comment]
@EvanDurfee I found out what causes this bug. Fix coming soon.™
