### ISSUE TITLE
Allow `zsnap install` command to auto-add plugins permanently

### ISSUE THREAD

**Issue by xenoterracide** [marlonrichert/zsh-snap#95]
I was just thinking, instead of chronically edit my `~/.zshrc` it would be awesome if I could write `znap install whatever` and have it automagically add it to a “config file”. 

Installing it specifically into `~/.zshrc` would be a bad idea, because I install that via a `yadm` template at the moment. So the `~/.zshrc` is not my source.

**Comment by marlonrichert** [comment]
Well, if not in `.zshrc`, then where? It’s a nice idea, but for this to be possible to implement, you would have to be a bit more specific on how this should actually work. 🙂

**Comment by xenoterracide** [comment]
I don't know, maybe, I'd probably put it in either .local/share/znap/ or .config/znap/ simply because that follows the xdg spec.

**Comment by marlonrichert** [comment]
Yes, that makes sense. I feel like it kind of ties in with #41.

I'm not sure if it's entirely feasible, though. For many plugins, it matters significant at what point they are loaded or the order in which they are loaded. It feels to me like this could easily cause more problems than it's worth.

**Comment by marlonrichert** [comment]
I experimented with this a bit, but in the end, decided against it:
* `znap install` currently finds and installs executables and completion functions. In many plugin repos, the only executable is a test script, which is not what you want to install. I don't want to abandon this use case for `znap install`: to put things in your `$path` and `$fpath`.
* The order in which plugins and other statements in your dotfiles are executed matters. I prefer to make the user think about what they're doing and make them decide explicitly what they want do. Doing things automagically all too easily leads to bad results.
